feat: Implemented commands-history
gemini-testing/hermione pull request #565
Opened 2021-06-07 12:48 UTC by unlok

TODO: 

- [ ] add info to the doc

2021-06-15 11:51 UTC, DudaGod requested changes
Текущие проблемы:
- опции `saveHistoryOnError` и `saveHistoryOnTestTimeout` сейчас явно не работают. Если теперь сохраняем историю только для всех тестов, то давай их явно выгасим;
- нет оверврайта команды `overwriteCommand`
- вызов коллбека внутри обертки addCommand выполняется с неправильной передачей аргументов (судя по коду)
- сломан один из тестов влитых в прошлом PR-е (чтобы не падал нужно обновить зависимости, а именно configparser)

2021-06-15 11:51 UTC, DudaGod commented on lib/browser/history/index.js
> +            () => wrapper.apply(wdioBrowser, args),
У тебя же тут указанная мной обертка вызовется только с одним аргументом в виде массива.

Т.е. выглядит так, что если я добавлю команду:
```
browser.addCommand('foo', (a, b, c) => {...});
```

То вызов функции:
```
browser.foo(1, 2, 3);
```
вызовет мой обработчик с `a = [1, 2, 3]`. А я ожидал не этого.

2021-06-15 11:51 UTC, DudaGod commented on lib/browser/history/index.js
> +        const decoratedWrapper = async (...args) => runWithHooks(
а для чего ты тут указываешь `async`? Ты же явно внутри этой функции ничего не await-ишь, а просто возвращаешь из нее промис. Соответственно вызывающий эту функцию должен просто `await` указать.

2021-06-15 11:51 UTC, DudaGod commented on lib/browser/history/index.js
> +    overwriteAddCommand(wdioBrowser, callstack);
А где overwrite команды `overwriteCommand`?
Ведь я могу заоверврайть одну из дефолтных команд и добавить какие-то новые аргументы, которые она может принимать. И более того я могу не вызывать команду, которую я заоверврайтил и тогда история вообще о таком вызове ничего не узнает.

2021-06-15 11:51 UTC, DudaGod commented on lib/browser/history/index.js
> +        () => origFn(...args),
А почему ты не вызываешь коллбек с интансом браузера? Или это происходит под капотом wdio (т.е. функция уже с забиндженым контекстом)?

2021-06-15 11:51 UTC, DudaGod commented on lib/browser/history/utils.js
> +};
А почему не использовать уже имеющуюся у нас логику нормализации аргументов? - https://github.com/gemini-testing/hermione/blob/master/lib/utils/history-utils.js#L10-L18

2021-06-15 11:51 UTC, DudaGod commented on lib/browser/history/index.js
> +    wdioBrowser.overwriteCommand(name, async (origFn, ...args) => runWithHooks(
Вызов `runWithHooks` был бы немного понятнее если передавать в него объект и явно указывать, какой коллбек является `before`, какой `after` и какой основной вызов.

2021-06-15 11:51 UTC, DudaGod commented on lib/browser/history/utils.js
> +    .finally(after);
А почему решил на промисах написать, а не на async-await?

2021-06-15 11:51 UTC, DudaGod commented on test/lib/browser/existing-browser.js
> +                history.initCommandHistoryForSession.restore();
Вверху есть общий `afterEach` с restore для всех стабов и спаев. Тут явно можно не вызывать.

2021-06-15 11:51 UTC, DudaGod commented on test/lib/browser/existing-browser.js
> +            it('should init commands-history if it is on', async () => {
я бы назвал - `should saves history of executed commands if it is enabled`. Так же намного понятнее, что конкретно происходит под капотом, чем назвать +/- так же как вызываемый метод.

2021-06-15 11:51 UTC, DudaGod commented on test/lib/browser/history/callstack.js
> +});
🔥

2021-06-15 11:51 UTC, DudaGod commented on test/lib/browser/history/index.js
> +    describe('index', () => {
о чем говорит этот `describe`?

2021-06-15 11:51 UTC, DudaGod commented on test/lib/browser/history/index.js
> +                assert.propertyVal(node, 's', 'b');
а проверить, что аргумент передались?

2021-06-15 11:51 UTC, DudaGod commented on test/lib/browser/history/index.js
> +            });
Нужно еще пару тестов написать, что коллбек реально вызовется с контекстом браузера и что правильно передадутся все аргументы.

2021-06-15 11:51 UTC, DudaGod commented on test/lib/browser/history/index.js
> +                assert.equal(res, 'result');
а что ты этой проверкой проверяешь в своем коде?

2021-06-15 11:51 UTC, DudaGod commented on test/lib/browser/history/index.js
> +            });
тут бы тоже проверить, что аргументы не потерялись. И ниже для элемента тоже.

2021-06-15 11:51 UTC, DudaGod commented on test/lib/config/browser-options.js
> +                assert.equal(config.browsers.b1.screenshotMode, 'auto');
вот это исправлять не нужно. Это работает корректно.

2021-06-15 15:39 UTC, unlok commented on README.md
> +Allows to save history of all executed commands. `true` by default.
Исходил из того, чтобы по дефолту работала история в html-reporter. + На скорость не влияет.

2021-06-15 15:39 UTC, unlok commented on README.md
> +#### saveHistory
Это теперь не работает. Нужно отрывать, про это есть таска.

2021-06-15 15:43 UTC, unlok commented on lib/browser/history/callstack.js
> +        currentNode.d = currentNode.te - currentNode.ts;
duration

2021-06-15 15:47 UTC, unlok commented on lib/browser/history/index.js
> +            () => wrapper.apply(wdioBrowser, args),
Это если бы был call, а apply сделает именно то, что ты ожидаешь.

2021-06-15 15:52 UTC, unlok commented on lib/browser/history/utils.js
> +};
Потому что она не подходит. Слишком много данных сохраняет + в следующих тасках ту логику можно выгашивать вместе с неработающей функциональностью.

2021-06-15 15:54 UTC, unlok commented on lib/browser/history/utils.js
> +const P = require('bluebird');
Я не пишу Promise, потому что Promise, это нативная реализация. Так себе история, когда видишь `Promise.map`. Выглядит как расширение стандартной реализации, хотя это не так. Согласен, тут нативных хватит.

2021-06-15 15:56 UTC, unlok commented on lib/browser/history/utils.js
> +    .finally(after);
Кмк, так лаконичнее получилось.

2021-06-15 16:56 UTC, DudaGod commented on lib/browser/history/index.js
> +            () => wrapper.apply(wdioBrowser, args),
А блин, точно. Я тупанул.

2021-06-15 17:04 UTC, DudaGod commented on README.md
> +#### saveHistory
Ты про этот тикет - https://nda.ya.ru/t/UNr28lEc3yzdDF?
Я его заводил, так как ожидал, что в рамках текущего PR-а решение будет реализовано немного другое. Ну и она не про выгашивание опций `saveHistoryOnTestTimeout` и `saveHistoryOnError`.

Почему бы их не оторвать в рамках этого же PR-а с учетом того, что они теперь не работают и не будут в будущем. Ну и ты добавил новую опцию `saveHistory`, которая их полностью заменяет. Кажется, логично их выгасить сразу же тут.

2021-06-18 12:45 UTC, DudaGod commented on README.md
> +        console.log(test.history);
Кстати, нужно еще тайпинги поправить. Добавить это поле сюда - https://github.com/gemini-testing/hermione/blob/9e8be0e9ea48d7b77e44b9713a8d0f1286eb857e/typings/index.d.ts#L198-L205

2021-06-22 10:34 UTC, unlok commented on README.md
> +#### saveHistory
Отписался в смежном ПРе. Удобнее выгашивать отдельным куском.

2021-06-22 13:06 UTC, unlok commented on lib/browser/history/index.js
> +        () => origFn(...args),
Да, там даже сложнее. Там под капотом биндится либо браузер либо элемент и если всегда биндить браузер - логика рассыпается.

2021-06-22 16:33 UTC, unlok commented on lib/browser/history/utils.js
> +exports.runWithHooks = ({fn, before, after}) => P
Оставил bluebird так как fakeTimers не дружит с нативными промисами. https://github.com/sinonjs/sinon/issues/738

2021-06-22 16:33 UTC, unlok commented
@DudaGod upd

2021-06-23 13:25 UTC, DudaGod approved these changes
Тесты посмотрел по диагонали.
В остальном /ok.
Не забудь сосквошить коммиты и выпустить альфа версию.

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/history/index.js
> +    [historyDataMap.IS_OVERWRITTEN]: Number(overwrite)
а почему бы не добавлять этот флаг только в команды которые реально были перезаписаны? А во все другие ничего не добавлять и по умолчанию это будет означать, что она не перезаписана.

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/history/utils.js
> +    CHILDREN: 'c'
🔥

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/browser.js
> +        this._addHistory();
А чего ты не перенес вызов `addHistory` выше `addCommands`? При этом предыдущий коммент пометил как `resolved`? Ниже при вызове `attach` тоже самое.

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/history/index.js
> +    overwriteOverwriteCommand(session, callstack);
По текущему определению функций в этом файле, я бы ожидал, что `overwriteOverwriteCommand` будет вызываться вторым. Или есть причины почему он последний?

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/history/index.js
> +            fn: () => wrapper.apply(session, [originFn, ...args]),
Вот здесь что-то не понял. Почему нельзя просто написать `args` для передачи массива? Т.е. так же как и в `addCommand`.

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/history/callstack.js
> +            [historyDataMap.CHILDREN]: []}
странно, что у тебя в конце расположилась фигурная скобка, а не строчкой ниже.

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/history/callstack.js
> +            console.warn('Cannot perform "leave". Stack is empty.');
Я бы написал более явно, что `... Stack of executed commands is empty`.
Ну и юзнул бы отдельный модуль с логгером - https://github.com/gemini-testing/hermione/blob/master/lib/utils/logger.js. Понятно, что там тот же `warn` под капотом, но его проще тестировать.

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/history/utils.js
> +    if (name === 'execute') {
Тоже можно было бы в константу унести, как и максимальную длину - 50.

2021-06-23 13:25 UTC, DudaGod commented on lib/browser/history/utils.js
> +const _ = require('lodash');
А где `use strict`?

2021-06-23 13:25 UTC, DudaGod commented on lib/runner/test-runner/regular-test-runner.js
> +        this._test.history = history;
А нужно ли сохранять это поле если я явно отключил опцию `saveHistory`?

2021-06-23 13:25 UTC, DudaGod commented on test/lib/browser/existing-browser.js
> +                history.initCommandHistory.restore();
вроде бы верхнеуровневый `afterEach` в этом файле с вызовом `sandob.restore` должен заресторить твой spy. Т.е. не нужно явно еще один писать.

2021-06-23 13:40 UTC, unlok commented on lib/browser/history/index.js
> +    overwriteOverwriteCommand(session, callstack);
Да, эта команда участвует в переопределении команд в **overwriteBrowserCommands** и **overwriteElementCommands**. Тогда в истории команд это уже будут **overwrite: true** команды и каждый возов url (например) будет превращаться в серию из двух команд url -> url.
Предполагается, что наша логика про оверврайт команд не должна фигурировать в истории.

2021-06-23 13:41 UTC, unlok commented on lib/runner/test-runner/regular-test-runner.js
> +        this._test.history = history;
Я специально сделал это поле консистентным. И даже когда команда не включена там будет пустой массив, чтобы потом не пришлось писать ифаки.

2021-06-24 08:20 UTC, unlok commented on typings/index.d.ts
> +        history: History;
Логика написана так, что при выключенном плагине тут будет пустой массив.

2021-06-24 08:20 UTC, unlok commented on lib/browser/history/index.js
> +    [historyDataMap.IS_OVERWRITTEN]: Number(overwrite)
Да, звучит логично.

2021-06-24 08:45 UTC, merged