fix(worker/test-runner): take the error screenshot on every test fail
gemini-testing/hermione pull request #622
Opened 2021-11-15 22:22 UTC by OldSkyTree

2021-12-01 10:15 UTC, DudaGod commented on lib/worker/runner/test-runner/execution-thread.js
> +        return fnPromise;
А почему просто в `finally` не перенести - https://github.com/gemini-testing/hermione/pull/622/files#diff-5713095e8f8980021ccffaa090363e813423457f63b741a6c752b395da35a323R31 ?

Ну и я все таки предлагаю завести отдельную опцию сохранения скриншотов страницы при падении ассертов скриншотами. Которая должна включаться отдельно для каждого браузера. Дело в том, что в тачевых браузерах скриншот всей страницы может выполняться очень долго (10+ секунд).

2022-01-17 11:49 UTC, DudaGod requested changes
Текущие проблемы:
- нет опции переключения режима: viewport vs full page
- есть ошибки в коде
- не хватает тестов (посмотрел не все, но уже вижу, что их не хватает). Проверь самостоятельно, что весь код протестирован.

2022-01-17 11:49 UTC, DudaGod commented on lib/worker/runner/test-runner/one-time-screenshooter.js
>              logger.warn(`WARN: Failed to take screenshot on reject: ${e}`);
в моей голове `reject` - это про падение теста с ошибкой. В случае когда присутствует дифф в скриншоте, то сообщение должно быть немного другим. Ну либо сделать сообщение более общее.

2022-01-17 11:49 UTC, DudaGod commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +                .call(this)
А нафига нам теперь этот `Promise.method` и `call` с `this`?
Кажется проще запромисифаить метод и на нем вызвать `timeout`.

2022-01-17 11:49 UTC, DudaGod commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        });
Что если у меня часть элементов выпадает за вьюпорт? Я про опцию `allowViewportOverflow`? Почему бы ее тоже в `true` не выставить?

2022-01-17 11:49 UTC, DudaGod commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        const page = await this._browser.prepareScreenshot(null, {
почему первый аргумент `null`? Выглядит как очень корявое API. Вроде бы говорили про то, что можно передать либо селектор, либо специальный объект с координатами.

2022-01-17 11:49 UTC, DudaGod commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +            allowViewportOverflow: true
Интересно почему тут передаешь `allowViewportOverflow`, а выше нет?

2022-01-17 11:49 UTC, DudaGod commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        await image.save(imageInfo.path);
А зачем нам сохранять скриншот на fs и тратить на это время? Почему бы не собрать как и раньше `base64` и его размер?

2022-01-17 11:49 UTC, DudaGod commented on test/lib/worker/runner/test-runner/execution-thread.js
> +            it('should extend hermione context with page screenshot if there are assert errors', async () => {
что такое `assert error`? Напомню, что есть вызов `assert.equal`, а есть `assertView` и они оба матчатся под твое описание.

2022-01-17 11:49 UTC, DudaGod commented on lib/worker/runner/test-runner/execution-thread.js
> +                return this._screenshooter.extendWithPageScreenshot(this._hermioneCtx);
А зачем так странно прокидывать `hermioneCtx`? Почему его просто не передать при создании инстанса?

2022-01-17 11:49 UTC, DudaGod commented on lib/worker/runner/test-runner/one-time-screenshooter.js
>      async extendWithPageScreenshot(error) {
Почему тут у тебя аргумент все еще `error` называется?

2022-01-17 11:49 UTC, DudaGod commented on test/lib/worker/runner/test-runner/execution-thread.js
> +            });
А почему предыдущий тест удалил?
У тебя же тут 2 кейса проверить нужно: тест упал или есть диффы при выполнении `assertView`.

А еще не вижу теста с проверкой опции - `screenshotOnAssertReject` (ее нужно переименовать кстати). Т.е. кейс когда опция отключена.

2022-01-25 12:46 UTC, OldSkyTree commented on lib/worker/runner/test-runner/index.js
> +            throw Object.assign(error, {screenshot: hermioneCtx.screenshot}, results);
Как ты помнишь, сейчас скриншот снимается на падение и сохраненный скриншот записывается в свойство объекта ошибки [здесь](https://github.com/gemini-testing/hermione/blob/master/lib/worker/runner/test-runner/execution-thread.js#L44).

Теперь же, я снимаю скриншот и на падение теста с `assert view`. В отличие от прочих ошибок, здесь сам объект ошибки создается позже, [здесь](https://github.com/gemini-testing/hermione/blob/master/lib/worker/runner/test-runner/index.js#L68). Поэтому мне нужно `доствить` снятый скриншот до созданного объекта ошибки, для чего я решил использовать `hermioneContext`.

2022-01-25 12:47 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +
убрал

2022-01-25 12:52 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
>              logger.warn(`WARN: Failed to take screenshot on reject: ${e}`);
исправил

2022-01-25 12:53 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        const page = await this._browser.prepareScreenshot(null, {
исправил

2022-01-25 12:55 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +            allowViewportOverflow: true
я кажется изначально его не передавал, а потом именно в месте `capture` скриншота увидел проблемы в тестах, поэтому только тут и добавил

2022-01-25 13:00 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        });
выставил

2022-01-25 13:19 UTC, OldSkyTree commented on lib/worker/runner/test-runner/execution-thread.js
> +                return this._screenshooter.extendWithPageScreenshot(this._hermioneCtx);
Ну, с учетом моих изменений, ты прав, теперь более правильно заранее прокидывать контекст

2022-01-25 15:01 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
>      async extendWithPageScreenshot(error) {
исправил

2022-01-25 15:05 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +                .call(this)
Нужно было обернуть стандартный промис в промис из `bluebird`. Это сделать нужно, поэтому оставлю, но буду использовать [Promise.resolve](http://bluebirdjs.com/docs/api/promise.resolve.html). Предвосхищая вопрос, отвечу, что оно не должно проглатывать ошибки, поэтому вызов сократится до следующего:
```
const screenshot = await Promise.resolve(this._makePageScreenshot).timeout(...);
```

2022-02-02 10:50 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        await image.save(imageInfo.path);
Договорились оставить как есть.

2022-02-08 13:16 UTC, DudaGod requested changes
Проблемы описал в комментах.
Их все еще много =(

2022-02-08 13:16 UTC, DudaGod commented on lib/worker/runner/test-runner/index.js
> +            throw Object.assign(error, {screenshot: hermioneCtx.screenshot}, results);
Если у нас `screenshooter` снимает только один скриншот при проблеме в тесте, то почему мы не можем добавить в него метод с помощью которого он вернет снятый скриншот? Тогда ничего прокидывать через `hermioneCtx` не придется. Нужно будет всего лишь вызвать этот метод здесь - https://github.com/gemini-testing/hermione/blob/master/lib/worker/runner/test-runner/index.js#L68 и докинуть его в ошибку.

2022-02-08 13:16 UTC, DudaGod commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            assert.calledOnce(ScreenShooter.prototype.capture);
А проверка на аргументы где?

2022-02-09 10:43 UTC, OldSkyTree commented on lib/worker/runner/test-runner/execution-thread.js
> +                return this._screenshooter.captureScreenshot();
Потому что ты предложил не передавать объект для расширения в метод `extendWithPageScreenshot`, а передавать его в конструктор, с чем я согласился. Но в таком случае возникал вопрос, а что тут собственно расширяется?

2022-02-09 10:44 UTC, OldSkyTree commented on README.md
> +`screenshotOnAssertViewFail`| Allows to attach a screenshot of a current page on assert view test fail. Default value is `false`.
Попробую переписать как-то понятнее

2022-02-09 10:46 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        this._expandable = expandable;
потому что классу все равно к какому объекту добавлять скриншот, раньше ведь был объект ошибки, теперь вот контекст гермионы, позже будет что-то еще

2022-02-09 10:49 UTC, OldSkyTree commented on lib/worker/runner/test-runner/execution-thread.js
> -        return fnPromise.tapCatch((e) => this._screenshooter.extendWithPageScreenshot(e));
Не совсем. Именно в ошибке, возвращаемой `ExecutionThread`, этой информации о скриншоте не будет. Но эта ошибка дальше будет возвращаться классом `TestRunner`, который и вызывает `ExecutionThread`. Именно там я добавляю инфу о скриншоте к этой ошибке.

Поэтому по сути, API не изменилось

2022-02-09 11:23 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +            _.assignIn(this._expandable, {screenshot});
я так и делаю чуть дальше по коду. hermioneCtx лишь транспорт для скриншота, но ты об этом чуть позже отписал и предложил альтернативу

2022-02-09 11:26 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +                .then(image => this._saveImage(image))
`one-time-screenshooter` ведь используется лишь при снятии скриншота на reject. Как раз мой случай

2022-02-09 11:28 UTC, OldSkyTree commented on test/lib/worker/runner/test-runner/execution-thread.js
> +                assert.calledOnce(OneTimeScreenshooter.prototype.captureScreenshot);
он и так попадает и, более того, на это есть [тест](https://github.com/gemini-testing/hermione/pull/622/files#diff-a3a10138147a67aa63bd544be1a0112f2ffda308281be616ee756480afcbd4d3R636)

2022-02-09 11:33 UTC, OldSkyTree commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            assert.calledOnce(ScreenShooter.prototype.capture);
добавил

2022-02-09 15:09 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        if (!this._config.screenshotOnReject || this._expandable.screenshot || this._screenshotTaken) {
Изначально опция `screenshotOnAssertViewFail` задумывалась как подопция `screenshotOnReject`, поэтому в этом плане все логично. Тут видимо вопрос о понятности значения опции.

2022-02-15 10:42 UTC, OldSkyTree commented
Рассматривал вариант с добавлением опции `takeScreenshotOnFails` и транслированием в неё опции `screenshotOnReject`, пробовал сделать это следующим образом:
```javascript
const {option} = require('gemini-configparser');

function defaultFactory(param) {
    // defaultFactory возвращает дефолтное значение для параметра
    // если мы находимся в корне – то это значение из файла
    // если мы находимся в ветке браузера – то это значение из корня
}

{
    takeScreenshotOnFails: option({
        defaultValue: {},
        parseEnv: JSON.parse,
        parseCli: JSON.parse,
        validate: (value) => {
            if (!_.isPlainObject(value)) {
                throw new Error('"takeScreenshotOnFails" must be an object');
            }
        },
        map: (value, config, currNode) => {
            const defaultValue = defaultFactory('takeScreenshotOnFails');
    
            return {
                ...config === currNode ? defaultValue : defaultValue(config),
                notScreenshotFail: currNode.screenshotOnReject,
                ...value
            };
        }
    })
}
```

Но тут возникла проблема, что оно не совсем верно работало для опции браузера. То есть, в следующем примере:
```javascript
{
    takeScreenshotOnFails: {notScreenshotFail: false},
    browsers: {
        'some-browser': {}
    }
}
```
Значения получились бы такие:
```javascript
config.takeScreenshotOnFails.notScreenshotFail; // false
config.takeScreenshotOnFails.browser['some-browser'].notScreenshotFail; // true
```
Не придумал пока как это исправить.

2022-02-18 07:47 UTC, OldSkyTree commented
> Ну и тут как-то напутанно все

поправил

> В примере вот этот кусок кода странный - ...config === currNode ? defaultValue : defaultValue(config),. В defaultValue у тебя уже объект дефолтный, а ты его еще пытаешься вызвать как функцию.

Там нужно глянуть в код, `config === currNode` определяет где мы находимся – в корне или в узле `browsers`. в одном случае `defaultValue` – значение, а в другом – функция.

2022-03-01 01:06 UTC, OldSkyTree commented
По итогу сделал новую опцию `takeScreenshotOnFails` отдельно от старой `screenshotOnReject`. Старая опция теперь `deprecated`, для это необходим функционал, добавленный в [пулл реквесте](https://github.com/gemini-testing/configparser/pull/24). Связь между опциями реализовал в [BrowserConfig](https://github.com/gemini-testing/hermione/blob/master/lib/config/browser-config.js#L6).

2022-03-02 15:07 UTC, DudaGod reviewed
Все еще есть вопросы.

2022-03-02 15:07 UTC, DudaGod commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            assert.calledOnceWith(ScreenShooter.prototype.capture, {foo: 'bar'});
А где опции, которые идут третим аргументом?

2022-03-02 15:07 UTC, DudaGod commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +    describe('captureErrorScreenshot', () => {
Я тут ожидал увидеть пачку тестов про новую функциональность со снятием полного скриншота. Но тут присутствует только проверка, что вызывается метод `capture`. Но ведь этого не достаточно. Где тесты про:
- вызов `evalScript` с корректными аргументами
- использование результата `evalScript` при вызове `prepareScreenshot`
- вызов `capture` с захардкоженными опциями (речь про `compositeImage` и `allowViewportOverflow`). Вижу тест, что про вызов `capture` с результатом `prepareScreenshot`
- сохранение изображения в temp
- получение `base64` и `size` из сохраненная файла в temp

2022-03-02 23:21 UTC, OldSkyTree commented on test/lib/config/browser-options.js
> +    describe('screenshotOnRejectMode', () => {
Ухудшится качество кода и он станет сложнее, не думаю, что это тот случай, когда стоит экономить строки

2022-03-02 23:23 UTC, OldSkyTree commented on test/lib/config/browser-options.js
> +    describe('screenshotOnReject', () => {
В курсе, забыл выгасить оттуда. Не хотелось бы проверять отдельно, тесты по одной и той же опции в двух и более местах кажется плохой идеей

2022-03-02 23:24 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        const path = temp.path(Object.assign(tempOpts, {suffix: '.png'}));
Мы ведь не вызываем никакой `assertView` для снятия скриншота.

2022-03-02 23:27 UTC, OldSkyTree commented on lib/config/options-builder.js
> +        return opts.isDeprecated ? deprecatedOption(name, booleanOptionConfig) : option(booleanOptionConfig);
Потому что в уже созданной опции нельзя переопределить `validate`.

2022-03-02 23:32 UTC, OldSkyTree commented on lib/config/browser-options.js
> +            })
Не заведется. Дело в том, что дефолтное значение у нас такое: `{assertViewFail: false}`. Оно будет использовано, если пользователь ничего не указал. Но, если пользователь его переопределил, то возьмется именно указанное значение. То есть, если пользователь укажет `{assertView: true}`, то мы потеряем свойство `assertViewFail`, а нам нужно чтобы оно всегда было, поэтому мы будем его брать из дефолта.

2022-03-02 23:33 UTC, OldSkyTree commented on README.md
> +#### screenshotOnRejectMode
Указал: 
> * `viewport` – Default value.

2022-03-02 23:35 UTC, OldSkyTree commented on README.md
> +`screenshotOnReject`      | Allows to attach a screenshot of a current page on test fail. Default value is `true`. :warning: Option is deprecated! Use `takeScreenshotOnFails` instead.
Ты предлагаешь их тоже переименовать или как?

2022-03-02 23:41 UTC, OldSkyTree commented on README.md
> +`takeScreenshotOnFails`   | Options for setting up taking a screenshot of a test fail. Default value is `{assertFail: true, assertViewFail: false}`.
Я считаю, что название `assertFail` – удачное. Нельзя же тут до бесконечности уточнять. Назвать можно, например, просто `testFail`, но тогда будет непонятно зачем опция `assertViewFail`, ведь это тоже fail теста. Не называть же её каким-нибудь `testFailExceptAssertView`. Предлагаю просто внятно написать доку, чтобы из неё все было понятно и этого будет достаточно.

2022-03-03 01:02 UTC, OldSkyTree commented on lib/config/browser-options.js
> +}
Кажется, так лучше выделяется то, что функция возвращает функцию, а не просто значение. Если написать `() => () => 'lala'`, то иногда можно не углядеть.

2022-03-03 01:18 UTC, OldSkyTree commented on lib/config/index.js
> +                    takeScreenshotOnFails: {
Интересная идея, но что заметил – ни один из хинтов не пофиксили при релизе 4-й версии. Кажется, нужен способ гарантировать фикс этих вещей.

2022-03-03 01:31 UTC, OldSkyTree commented on lib/config/options-builder.js
> +        return opts.isDeprecated ? deprecatedOption(name, booleanOptionConfig) : option(booleanOptionConfig);
переделал немного, должно быть получше

2022-03-03 01:35 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        const path = temp.path(Object.assign(tempOpts, {suffix: '.png'}));
> А для чего мы тут повторно suffix проставляем? Он же вроде бы выставляется внутри вызова assertView.

В тесте ведь мог и не вызываться `assertView`.

2022-03-03 01:41 UTC, OldSkyTree commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +        const path = temp.path(Object.assign(tempOpts, {suffix: '.png'}));
> И не пойму для чего tempOpts модифицировать, который находится внутри синглтона RuntimeConfig.

Перенес практически один в один из assert-view, но ты прав, модифицировать его нет нужды.

2022-03-03 01:52 UTC, OldSkyTree commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
>          });
Я пробовал, так будет хуже, читаемость сильно понизится.

2022-03-03 01:53 UTC, OldSkyTree commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            const expandable = {};
забыл это поправить

2022-03-03 08:35 UTC, DudaGod commented on lib/config/options-builder.js
> +        return opts.isDeprecated ? deprecatedOption(name, booleanOptionConfig) : option(booleanOptionConfig);
> Потому что в уже созданной опции нельзя переопределить validate.

Так а почему `deprecatedOption` не может может декоратором над `option`?

2022-03-03 15:29 UTC, OldSkyTree commented on lib/config/options-builder.js
> +        return opts.isDeprecated ? deprecatedOption(name, booleanOptionConfig) : option(booleanOptionConfig);
я примерно так и переделал

2022-03-03 15:35 UTC, OldSkyTree commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +    describe('captureErrorScreenshot', () => {
То есть ты предлагаешь в тестах описать каждую строку из функции. Но тогда при любом чихе на код он будет ломаться и придется идти и править тесты. Мне это кажется немного странным.

2022-03-03 16:32 UTC, OldSkyTree commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            assert.calledOnceWith(ScreenShooter.prototype.capture, {foo: 'bar'});
обсудим это в треде ниже

2022-03-05 09:49 UTC, DudaGod reviewed
Что осталось:
- решить, что делаем с опциями `screenshotOnRejectMode` и `screenshotOnRejectTimeout` (подробнее в комментах отписал)
- решить, что делаем с возможностью указания deprecated опций. Сейчас не очень удобно реализовано (описал в комментах). Удобно было бы иметь такую возможность в самом `configparser`. Возможно стоит вынести в отдельную задачу
- вопросы к тестам

2022-03-05 09:49 UTC, DudaGod commented on lib/config/index.js
> +                    takeScreenshotOnFails: {
> А зачем так делать? Где происходит мердж на root уровне?

Ты вот на это не ответил.

> Интересная идея, но что заметил – ни один из хинтов не пофиксили при релизе 4-й версии. Кажется, нужен способ гарантировать фикс этих вещей.

Согласен. Можно подумать как это гарантировать.

2022-03-05 09:49 UTC, DudaGod commented on test/lib/config/browser-options.js
> +    describe('screenshotOnReject', () => {
> Не хотелось бы проверять отдельно, тесты по одной и той же опции в двух и более местах кажется плохой идеей

А почему тебе кажется, что это плохая идея? 
В текущем решении у нас получается дублирование 3 тестов. При этом мока дает нам возможность писать `describe` с одинаковыми тайтлами. И при запуске тестов они отобразятся вместе под одним тайтлом.

В данном случае я бы избавлялся от дублирования. Этот файл с тестами итак слишком гигантский.

2022-03-05 09:49 UTC, DudaGod commented on lib/worker/runner/test-runner/one-time-screenshooter.js
> +            if (this.getScreenshot()) {
Почему просто `this._screenshot` не заюзать? И ниже на одну строку тоже.

2022-03-05 09:49 UTC, DudaGod commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            const expandable = {};
Этот `expandable` все еще здесь.

2022-03-05 09:49 UTC, DudaGod commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            browser.prepareScreenshot.resolves({foo: 'bar'});
У тебя сейчас этот метод вообще никак не связан с `evalScript`. Т.е. я могу в твоем текущем коде вместо - `const pageSize = await this._getPageSize();` написать - `const pageSize = {}` и все будет работать. Тут нужно связь между методами с помощью `withArgs`.

2022-03-05 09:49 UTC, DudaGod commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            assert.calledOnceWith(ScreenShooter.prototype.capture, {foo: 'bar'});
> То есть ты предлагаешь в тестах описать каждую строку из функции. Но тогда при любом чихе на код он будет ломаться и придется идти и править тесты. Мне это кажется немного странным.

Я предлагаю описывать аргументы, которые важны для его корректной работы. Что будет если я не передам `captureElementFromTop: true`? Очевидно, что метод сломается и тесты мне об этом вообще ничего не сообщат. Но зато мне их не придется править - профит!

Основная цель тестов проверить, что после изменений разработчика код все еще работает корректно. В этом случае они цель свою не очень выполняют.

2022-03-05 09:49 UTC, DudaGod commented on test/lib/worker/runner/test-runner/one-time-screenshooter.js
> +            assert.calledOnceWith(ScreenShooter.prototype.capture, {foo: 'bar'});
Вот этого теста не вижу при снятии `fullpage` скриншота:

> получение base64 и size из сохраненного файла в temp

2022-03-05 09:49 UTC, DudaGod commented on typings/index.d.ts
> +        screenshotOnAssertViewFail: boolean;
Что это за опция?

2022-03-05 09:49 UTC, DudaGod commented
Еще конфликты поребейзить нужно

2022-03-09 22:37 UTC, OldSkyTree commented on test/lib/config/browser-options.js
> +    describe('screenshotOnReject', () => {
Кажется плохой, потому что они не отобразятся вместе под одним тайтлом, а будут разделены.

2022-03-10 22:35 UTC, OldSkyTree commented on README.md
> +`screenshotOnReject`      | Allows to attach a screenshot of a current page on test fail. Default value is `true`. :warning: Option is deprecated! Use `takeScreenshotOnFails` instead.
согласен, сделал

2022-03-10 22:36 UTC, OldSkyTree commented on README.md
> +`takeScreenshotOnFails`   | Options for setting up taking a screenshot of a test fail. Default value is `{assertFail: true, assertViewFail: false}`.
исправил

2022-03-10 22:37 UTC, OldSkyTree commented on lib/config/index.js
> +                    takeScreenshotOnFails: {
> Где происходит мердж на root уровне?

На root уровне ничего не мерджится, так как везде в гермионе мы работаем на уровне конфига браузера

2022-03-10 22:38 UTC, OldSkyTree commented on lib/config/options-builder.js
> +    function option(name, optionConfig, {isDeprecated}) {
переделал

2022-03-11 01:13 UTC, OldSkyTree commented
дополнительный ПР в configparser: https://github.com/gemini-testing/configparser/pull/26

2022-03-16 09:37 UTC, DudaGod approved these changes
Не забыть:
- выгасить .only
- пересесть на мастер configparser
- еще раз прогнать тесты в web4 перед влитием

В остальном /ok

2022-03-16 09:37 UTC, DudaGod commented on README.md
> +    - [takeScreenshotOnFailsTimeout](#takescreenshotonfailstimeout)
Я бы эти опции перечислял рядом с `takeScreenshotOnFails`. А то у тебя между ними влез `screenshotOnReject`

2022-03-16 09:37 UTC, DudaGod commented on README.md
> +`screenshotOnRejectTimeout`| Timeout for taking screenshot on test fail. Default value is `httpTimeout`. :warning: Option is deprecated! Use `takeScreenshotOnFailsTimeout` instead.
а эту опцию я бы описывал рядом со `screenshotOnReject`

2022-03-16 09:37 UTC, DudaGod commented on lib/config/index.js
> +                    takeScreenshotOnFails: {
Тут мысль была в том, что эту опцию могут использовать в плагинах. Предлагаю тут какой-то коммент оставить, чтобы не забыть в мажоре выгасить.

2022-03-16 09:37 UTC, DudaGod commented on test/lib/config/browser-options.js
> +describe.only('config browser-options', () => {
Аккуратнее с таким нужно.

2022-03-22 02:51 UTC, merged