feat: add element's assertView method
gemini-testing/hermione pull request #652
Opened 2022-08-16 11:21 UTC by KuznetsovRoman

Adds the ability to call element's assertView method like this:
```
it('element example', async ({browser}) => {
  await browser.url('https://npmjs.com');
  const elem = await browser.$('#main');
  await elem.assertView('plain', {}); // state and options only
});
```

2022-08-29 14:57 UTC, DudaGod requested changes
Нужно тесты поправить

2022-08-29 14:57 UTC, DudaGod commented on test/lib/browser/history/index.js
> +        it('should save element context while wrapping for "addCommand" with elemScope: true', async () => {
А зачем нам этот тест здесь? Кажется он из другого PR-а - https://github.com/gemini-testing/hermione/pull/651

2022-08-29 14:57 UTC, DudaGod commented on test/lib/browser/commands/assert-view/index.js
> +            elem.selector = selector;
А зачем ты тут сам выставляешь селектор? Давай эту логику унесем внутрь стаба команды `$`. Т.е. сюда - https://github.com/gemini-testing/hermione/blob/master/test/lib/browser/utils.js#L80

2022-08-29 14:57 UTC, DudaGod commented on test/lib/browser/commands/assert-view/index.js
> +        });
Тут бы по хорошему проверить все эти тесты (речь про тесты внутри `describe('assertView command'` для двух вариантов использования: вызов у браузера и вызов на элементе.

Посмотри пример в этих тестах - `https://github.com/gemini-testing/hermione/blob/master/test/lib/reporters/jsonl.js#L100-L176

2022-08-29 14:57 UTC, DudaGod commented on lib/browser/commands/assert-view/index.js
> +    }, true);
Проверил корректность работы на тестовом проекте с включенным плагином html-reporter (в режиме статического отчета и gui)? По идее никаких проблем быть не должно и скриншоты должны в отчете отображаться корректно.

2022-08-29 14:59 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/index.js
> +    }, true);
Проверил, работает

2022-08-29 15:08 UTC, KuznetsovRoman commented on test/lib/browser/history/index.js
> +        it('should save element context while wrapping for "addCommand" with elemScope: true', async () => {
Неправильно заребейзил. Исправил

2022-08-29 15:17 UTC, KuznetsovRoman commented on test/lib/browser/commands/assert-view/index.js
> +            elem.selector = selector;
Исправил

2022-08-30 09:12 UTC, DudaGod approved these changes
В остальном /ok
Не забудь отребейзится по мастеру.

2022-08-30 09:12 UTC, DudaGod commented on test/lib/browser/commands/assert-view/index.js
>      });
Я бы этот тест просто унес ниже в `forEach` и проверил отдельно с вызовами на браузере и на элементе.

2022-08-30 09:12 UTC, DudaGod commented on test/lib/browser/commands/assert-view/index.js
> +    it('should prepare screenshot for several selectors', async () => {
давай в названии явно укажем, что тут речь только про `browser scope`

2022-08-30 18:48 UTC, merged