Add base for typescript
gemini-testing/hermione pull request #661
Opened 2022-09-21 17:31 UTC by OldSkyTree

2022-11-03 08:23 UTC, DudaGod requested changes
Есть проблемы.

2022-11-03 08:23 UTC, DudaGod commented on .npmignore
> +lib
Зачем так игнорировать то? У нас же есть `files` в `package.json`. Давай явно паблишить только то что нужно

2022-11-03 08:23 UTC, DudaGod commented on .eslintignore
> -/lib/core/browser/client-scripts/calibrate.min.js
А зачем отсюда удалил?

2022-11-03 08:23 UTC, DudaGod commented on package.json
> +    "pretest": "npm run build",
А точно это нужно? Зачем мне каждый раз выполнять `build` перед выполнением `npm test`?

2022-11-03 08:23 UTC, DudaGod commented on package.json
> +    "preversion": "npm test",
А это зачем?

2022-11-03 08:23 UTC, DudaGod commented on package.json
> +    "postbuild": "npm run prepare-calibrate-script",
Зачем после каждого билда генерить этот скрипт? Его же нужно перед паблишем в npm только генерить

2022-11-03 08:23 UTC, DudaGod commented on package.json
> +    "prepublishOnly": "npm run build",
А почему используешь `prepublishOnly`, а не `prepack`, как мы юзаем в большинстве библиотек? Пример - https://github.com/gemini-testing/hermione-storybook/blob/master/package.json#L16.

Ну и где очистка лишнего перед сборкой?

2022-11-03 08:23 UTC, DudaGod commented on package.json
> +    "@tsconfig/node12": "^1.0.11",
А зачем нам этот пакет?
У нас же уже есть устоявшиеся опции, которые мы юзаем обычно - https://github.com/gemini-testing/hermione-storybook/blob/master/tsconfig.common.json.

2022-11-03 08:23 UTC, DudaGod commented on tsconfig.json
> +  "include": ["lib"],
А почему в `src` не переименовали? Ну и зачем ты в `build` еще и тесты загоняешь не пойму?

2022-11-03 09:32 UTC, OldSkyTree commented on .npmignore
> +lib
У нас нет `files` в `package.json`. Добавлять его – отдельная задача, тут я использую то, что уже есть.

2022-11-03 09:37 UTC, OldSkyTree commented on package.json
> +    "pretest": "npm run build",
Потому что тестирование выполняется на исходниках, собранных в папку `build`. Перед тестированием, нужно собрать изменения. Если хочется, то можно отдельно вызвать скрипт `test-unit`

2022-11-03 09:41 UTC, OldSkyTree commented on package.json
> +    "prepublishOnly": "npm run build",
А зачем это делать на `prepack`? У меня была цель лишь собрать исходники перед паблишем в npm. Для этого более чем достаточно `prepublishOnly`. 

> как мы юзаем в большинстве библиотек

Все-таки хочется понимать мотивацию, чем просто делать как везде

2022-11-03 09:44 UTC, DudaGod commented on .npmignore
> +lib
Не понял, а в чем сложность добавить пару строк? Я их даже за тебя написал:
```
"files": [
  "build"
],
```

В соседнем PR у нас поле `engines` в `package.json` тоже не было. Но ты его добавил - https://github.com/gemini-testing/configparser/pull/23/commits/c7d1c052d9a42e8c6777afd55adc8879319cb63c

2022-11-03 09:45 UTC, OldSkyTree commented on package.json
> +    "@tsconfig/node12": "^1.0.11",
Не знал про них, но из этого пакета определяются такие параметры как:
```
"compilerOptions": {
    "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
    "module": "commonjs",
    "target": "es2019",
  }
```

Лучше будет в будущем вынести эти устоявшиеся опции в отдельный пакет

2022-11-03 09:47 UTC, OldSkyTree commented on tsconfig.json
> +  "include": ["lib"],
> А почему в src не переименовали?

Нужно ли? Ничего критичного тут не вижу.

> Так это, почему сразу не сделать общую папку src и не сложить туда исходники с тестами?

Моя цель была добавить инфраструктуру для typescript, мне совсем не хотелось менять то, что не требуется для этого

2022-11-03 09:48 UTC, OldSkyTree commented on package.json
> +    "postbuild": "npm run prepare-calibrate-script",
Мне такой вариант казался более прозрачным. Но если хочешь, то могу это делать только на паблиш

2022-11-03 10:34 UTC, shadowusr commented on test/lib/browser-pool/index.js
> +const CoreBrowserPool = require('build/core/browser-pool');
А почему здесь и во всех остальных местах мы импортируем из build, почему мы не можем импортить из исходников? Я думаю, что импортировать что-либо из build – bad practice, мы явно не контролируем содержимое build и не должны от него зависеть

Здесь точно не пропущена точка? Перепроверил на всякий случай доку: https://nodejs.org/api/modules.html, модули, которые не начинаются с `.`, `..`, `/` ищутся в `node_modules`. Только не понял, как это раньше работало

2022-11-03 11:03 UTC, DudaGod commented on tsconfig.json
> +  "include": ["lib"],
> Нужно ли? Ничего критичного тут не вижу.

Я считаю, что да. Мы все свои пакеты на TS приводим к такой структуре.

> Моя цель была добавить инфраструктуру для typescript, мне совсем не хотелось менять то, что не требуется для этого

Мне кажется, что в данном случае правильно сразу:
- выстроить правильную структуру
- собирать весь код на js, т.е. тесты в том числе. Они тоже в будущем должны быть переписаны на TS

Как по мне это и будет базовая инфраструктура. Которая дальше позволяет переписывать код по кусочкам.

2022-11-03 11:08 UTC, DudaGod commented on test/lib/browser-pool/index.js
> +const CoreBrowserPool = require('build/core/browser-pool');
> Здесь точно не пропущена точка? Перепроверил на всякий случай доку: https://nodejs.org/api/modules.html, модули, которые не начинаются с ., .., / ищутся в node_modules. Только не понял, как это раньше работало

Оно работает за счет пакета [app-module-path](https://www.npmjs.com/package/app-module-path) используется тут - https://github.com/gemini-testing/hermione/blob/master/test/setup.js#L13

> А почему здесь и во всех остальных местах мы импортируем из build, почему мы не можем импортить из исходников? Я думаю, что импортировать что-либо из build – bad practice, мы явно не контролируем содержимое build и не должны от него зависеть

Кстати да. Согласен.

2022-11-03 13:50 UTC, OldSkyTree commented on test/lib/browser-pool/index.js
> +const CoreBrowserPool = require('build/core/browser-pool');
Это только в том случае, когда тесты смогут читать `ts`-файлы. Мы ведь планируем это все переписать на `ts`, поэтому не получится читать файлы из `lib`.

2022-11-03 13:50 UTC, OldSkyTree commented on test/lib/browser-pool/index.js
> +const CoreBrowserPool = require('build/core/browser-pool');
Поэтому я заранее все чтение файлов перенес на `build`

2022-11-03 14:09 UTC, DudaGod commented on test/lib/browser-pool/index.js
> +const CoreBrowserPool = require('build/core/browser-pool');
> Это только в том случае, когда тесты смогут читать ts-файлы. Мы ведь планируем это все переписать на ts, поэтому не получится читать файлы из lib.

Так это же легко решается. При запуске mocha с ts тестами нужно поднести `ts-node`, который будет в рантайме компилить тесты. Например вот так - `mocha -require ts-node/register ...`. В jest скорей всего тоже `ts-node` юзается, но он подключается не явно под капотом.

2022-11-03 14:22 UTC, OldSkyTree commented on package.json
> +    "pretest": "npm run build",
А ты не будешь делать еще один запуск `npm run build`, потому что ты будешь вызывать скрипт `test-unit` вместо `test` конкретно в этом случае

2022-11-03 14:40 UTC, DudaGod commented on package.json
> +    "pretest": "npm run build",
> А ты не будешь делать еще один запуск npm run build, потому что ты будешь вызывать скрипт test-unit вместо test конкретно в этом случае

Ну если я не буду тогда Жека запустит и ему больно будет. Почему лучше так не делать я аргументов накидал. Предлагаю поправить, либо объяснить для чего эта неявная сборка нам очень нужна.

2022-11-03 15:04 UTC, OldSkyTree commented on package.json
> +    "pretest": "npm run build",
Я могу сделать так как ты этого хочешь, но это все выглядит как вкусовщина, а не проблема.

2022-11-03 15:14 UTC, DudaGod commented on package.json
> +    "pretest": "npm run build",
> Я могу сделать так как ты этого хочешь, но это все выглядит как вкусовщина, а не проблема.

Предлагаю вернуться к аргументированной беседе если это еще возможно. Мои аргументы почему этот `pretest` по моему мнению не нужен:
- неявная сборка при запуске тестов
- при вызове `npm run build && npm test` скрипт `build` вызовется дважды. И вызов этого `tsc --build` не бесплатная операция
- обычно при разработке запускается `tsc` в режиме вотчинга и затем запускаешь тесты. При этом можно запускать либо просто скрипт `test`, либо отдельно скрипт `unit`. В итоге при запуске `test` запустится еще раз `tsc`, хотя у меня итак уже вотчер работу работает

Почему `pretest` может быть полезен:
- вызываешь `npm test` и не нужно помнить, что нужно вызвать `npm build`. Возможно полезно в CI. Но почему в CI нельзя вызвать `npm run build && npm test` не очень понятно.

Ну я и не говорил, что это какая-то глобальная проблема. Просто хочется, чтобы скрипты работали ожидаемо.

2022-11-06 22:47 UTC, OldSkyTree commented on package.json
> +    "pretest": "npm run build",
Хорошо. Но в таком случае все твои представленные проблемы решаются тем, что ты вызываешь скрипт `test-unit`.

Скрипт `test` для меня выглядит как контрольная проверка всего проекта, которая и соберет его, и протестирует юнит-тестами и линтеры запустит.

> Но почему в CI нельзя вызвать npm run build && npm test не очень понятно.

Можно, но по прежнему непонятно чем хуже использовать для этого `pretest`.

2022-11-06 22:50 UTC, OldSkyTree commented on package.json
> +    "prepublishOnly": "npm run build",
Согласен, давай сделаем на `prepack`. Очистку добавлю.

2022-11-06 23:12 UTC, OldSkyTree commented on package.json
> +    "postbuild": "npm run prepare-calibrate-script",
Решил оставить вариант с вызовом скрипта `prepare-calibrate-script` на `postbuild`. На это есть несколько причин.

Минифицированный файл [реквайрится](https://github.com/gemini-testing/hermione/blob/master/lib/core/calibrator/index.js#L10) при инициализации [calibrator'a](https://github.com/gemini-testing/hermione/blob/master/lib/core/calibrator/index.js), поэтому он нужен не только при непосредственном запуске гермионы, но и при выполнении юнит-тестов, так как они тоже реквайрят файлы гермионы.

Раньше файл минифицировался сразу после установки зависимостей и в дальнейшем с ним ничего не происходило, поэтому этого было достаточно (хотя тут была бы проблема при его изменении, но его крайне редко трогали).

Сейчас же минификацию нельзя выполнить сразу после установки зависимостей, ведь минифицировать нужно транспилированный файл, а не исходник, поэтому необходимо было найти другой скрипт в котором можно было бы выполнять минификацию. Дельным решением было бы вызывать его на публикацию пакета, как ты и предложил, но это также не подойдет, ведь как я указал выше, этот файл также нужен при выполнении тестов. Стоит добавить, что при удалении папки с транспилированными файлами (по какой бы то ни было причине), минификацию нужно выполнять снова. 

Итого, с учетом всего вышесказанного, а также того, что минификация занимает по времени доли секунд, я решил выполнять минификацию на скрипте `postbuild`, сразу после сборки проекта. На мой взгляд, это достаточно прозрачный способ, который не заставляет запоминать все скрипты, после которых должна будет выполниться минификация, а также он должен избавить от всех потенциальных проблем.

2022-11-06 23:20 UTC, OldSkyTree commented on test/lib/browser-pool/index.js
> +const CoreBrowserPool = require('build/core/browser-pool');
> А почему здесь и во всех остальных местах мы импортируем из build, почему мы не можем импортить из исходников? Я думаю, что импортировать что-либо из build – bad practice, мы явно не контролируем содержимое build и не должны от него зависеть.

Ясно вижу ситуацию, когда из-за неверно настроенного проекта в папке `build` получилось совсем не то, что ожидалось на самом деле. Тесты это, естественно не отловили, ведь мы тестируем не папку `build` (то, что поедет в прод), а папку `lib`.

Да, можно сказать, что нужно лишь один раз правильно настроить проект и тогда все в собранных файлах должно быть хорошо, но тем не менее, мне кажется правильным тестировать именно то, что мы получаем в итоге.

2022-11-06 23:30 UTC, OldSkyTree commented on tsconfig.json
> +  "include": ["lib"],
Согласен с тем, чтобы переименовать папку `lib` в `src`. Тесты же предлагаю не перемещать, а оставить в той же месте где они сейчас и находятся. Считаю, что нецелесообразно внедрять возможность писать тесты на `TS` на `mocha`.

> Они тоже в будущем должны быть переписаны на TS

Не просто на `TS`, а еще и на `jest`. Мне кажется совершенно неблагодарной работой переписать все тесты на `TS`, а затем снова переписать все тесты на `jest`. Гораздо лучше будет создать в папке `src` папку `test` и добавлять туда тесты уже на `TS+jest`, постепенно переписывая туда старые тесты. Однако соответствующую инфраструктуру предлагаю добавить тому, кто будет внедрять `jest`.

2022-11-06 23:31 UTC, OldSkyTree commented on test/lib/browser-pool/index.js
> +const CoreBrowserPool = require('build/core/browser-pool');
Кроме того, эта проблема естественным образом уйдет после переписывания тестов на TS

2022-11-06 23:38 UTC, OldSkyTree commented on package.json
> +    "@tsconfig/node12": "^1.0.11",
> А они нам нужны? Ты какие-то фичи хотел из es2019 и es2020 юзнуть?

Если у нас минимальная нода для гермионы это 12, то с заделом на возможность добавлять фичи из 12 ноды я оставлю настройку для `es2019`

2022-11-07 00:35 UTC, OldSkyTree commented on package.json
> +    "prepublishOnly": "npm run build",
Обнаружил проблему с использованием `prepack`. `prepack` [вызывается](https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-scripts), кроме команд `pack` и `publish` еще и когда пакет устанавливается как `git`-зависимость. В связи с этим, чтобы не ломать привычный флоу для тестирования пакета, оставлю пока что `prepublishOnly`, то возникновения реальной необходимости вызывать сборку непосредственно на команду `pack`.

2022-11-07 06:19 UTC, shadowusr commented on test/lib/browser-pool/index.js
> +const CoreBrowserPool = require('build/core/browser-pool');
> Ясно вижу ситуацию, когда из-за неверно настроенного проекта в папке build получилось совсем не то, что ожидалось на самом деле. Тесты это, естественно не отловили, ведь мы тестируем не папку build (то, что поедет в прод), а папку lib.

Здесь не согласен – мы хотим тестировать свой собственный код, который лежит в lib/. Это юнит-тесты. Твой аргумент – это по сути предложение в своих юнит тестах тестировать еще и tsc-компилятор и наш конфиг, правильно ли все собралось. Так никто не делает. Если у нас прямо есть подозрения к процессу сборки, можно писать e2e тесты, которые будут тестировать весь сервис

> Кроме того, эта проблема естественным образом уйдет после переписывания тестов на TS

То есть в итоге мы все таки будем тестировать lib/, а не build/, тогда почему не сделать это сейчас?

В целом я считаю, что возможность писать тесты на TS входит в базовую инфраструктуру TS, было бы классно, чтобы эта возможность появилась сразу, как описывал Дима выше

2022-11-07 08:54 UTC, DudaGod commented on package.json
> +    "pretest": "npm run build",
> Хорошо. Но в таком случае все твои представленные проблемы решаются тем, что ты вызываешь скрипт test-unit.

У меня нет проблем ) Проблема в скрипте и в неявном вызове сборки. Ну и нам же эта сборка вообще не нужна тут. Линтер выполняется на исходниках. Ну и тесты мы должны запускать на исходниках с компиляцией в рантайме (как в jest).

> Можно, но по прежнему непонятно чем хуже использовать для этого pretest.

Ну выше же объяснил в чем проблема. Твой аргумент сводится к тому, что не запускай скрипт `test` локально и будет тебе счастье. По моему это крайне слабый аргумент.

> На данный момент оставлю вариант с pretest, посмотрю, покажет ли он себя с плохой стороны.

Предлагаю не оставлять его, так как в нем нет смысла. Он для тестов не нужен.

2022-11-07 09:29 UTC, DudaGod commented on tsconfig.json
> +  "include": ["lib"],
> Тесты же предлагаю не перемещать, а оставить в той же месте где они сейчас и находятся.

Ну ок, можем не перемещать и оставить в папке `test`.

> Считаю, что нецелесообразно внедрять возможность писать тесты на TS на mocha.

А в чем нецелесообразность то? Mocha вполне нормальный инструмент позволяющий писать тесты на TS. При переписывании на jest нужно будет просто используемые методы API поменять. Скорей всего даже кодмод есть для этого дела. Но сами типы из исходников гермионы останутся абсолютно такими же.

> Не просто на TS, а еще и на jest. Мне кажется совершенно неблагодарной работой переписать все тесты на TS, а затем снова переписать все тесты на jest. Гораздо лучше будет создать в папке src папку test и добавлять туда тесты уже на TS+jest, постепенно переписывая туда старые тесты. Однако соответствующую инфраструктуру предлагаю добавить тому, кто будет внедрять jest.

Я не пойму зачем нам обязательно сразу же на jest переходить? Мы же можем просто начать писать тесты на TS на моке. Переходу с mocha на jest это вообще никак не мешает же.

Еще раз уточню, что я просто предлагаю добавить компиляцию тестов с `allowJs: true`, ну и компиляцию в рантайме при запуске тестов. Это позволит писать тесты на TS с использованием mocha после данного PR-а. В котором ты внедряешь инфраструктуру для использования TS.

2023-03-12 22:04 UTC, closed without merging