feat: add default waitForExist on element command
gemini-testing/hermione pull request #664
Opened 2022-10-04 07:26 UTC by KuznetsovRoman

2022-10-12 10:05 UTC, DudaGod requested changes
Текущее решение очень хрупкое. Полазил в коде и выглядит так, что нашу проблему решает использование setImplicitTimeout - https://webdriver.io/docs/api/jsonwp/#setimplicittimeout. Он используется внутри команд и $$. Но не вижу использования внутри `react$` и `react$$`. Возможно в них решается как-то по другому.

Предлагаю завести issue в wdio и пообщаться с Броманом. В issue нужно принести все детали. Как работает сейчас и как хочется, чтобы работало. И договорится о добавлении необходимой логики в wdio. Если все решается с помощью установки implicit таймаута, то можно issue не заводить.

2022-10-12 12:23 UTC, KuznetsovRoman commented on lib/browser/with-existing/commands.js
> +const shouldNotWrapCommands = [
[setImplicitTimeout](https://webdriver.io/docs/api/jsonwp/#setimplicittimeout) выглядит как что-то похожее на то, что нужно, но он есть только в JSONWP

Попробовал что-то придумать с [customLocatorStrategy](https://webdriver.io/docs/api/browser/custom$), пример падает по причине TypeError: browser.addLocatorStrategy is not a function (по сути он там undefined)

2022-10-14 10:07 UTC, KuznetsovRoman commented on lib/browser/with-existing/commands.js
> +const shouldNotWrapCommands = [
Заюзал [setTimeout](https://webdriver.io/docs/api/browser/setTimeout)

2022-10-14 11:34 UTC, sipayRT commented on lib/config/browser-options.js
> +        waitforExist: options.optionalNonNegativeInteger('waitforExist')
без слова `timeout` по названию опции не понять что она делает
у нас сейчас есть еще и опция waitTimeout - https://github.com/gemini-testing/hermione#waittimeout

кажется, их уже пора собирать в кучу :)

2022-10-14 15:07 UTC, DudaGod commented on lib/browser/browser.js
> +        this._addImplicitTimeout();
Этот таймаут нужно вызывать только в мастер процессе т.е. в new-browser, примерно тут - https://github.com/gemini-testing/hermione/blob/master/lib/browser/new-browser.js#L31-L32.

Ну и нужно проверить работу в `edge`, т.к. установка page-load таймаута в нем не работает - https://github.com/gemini-testing/hermione/blob/master/lib/browser/new-browser.js#L63-L70

2022-10-27 07:59 UTC, KuznetsovRoman commented
Установить таймаут неявного ожидания элементов можно установив параметр `waitTimeout` в файле `.hermione.conf.js`

2022-10-27 18:35 UTC, xrsd commented on test/lib/browser/commands/assert-view/index.js
> +    it('should wair for all selectors to exist', async () => {
`should wait`

2022-10-27 18:50 UTC, xrsd commented on lib/browser/commands/assert-view/index.js
>          return assertView(state, selectors, opts);
Кстати, вот в таких кейсах еще надо всегда смотреть не изменяется ли конечное поведение с точки зрения выкидывания исключений. Казалось бы, что такого, добавили всего одну строку и всё. Но из-за того, что раньше вся логика была в `assertView`, то теоретически изнутри `assertView` могла лететь какая-нибудь `AssertViewError`, а когда ты добавляешь свою строку, то при отсутствии селекторов теперь ошибка может лететь совершенно другая (в данном случае от webdriverio).

Но я посмотрел в код на глубину, судя по всему, при несуществующих селекторах мы раньше падали бы [тут](https://github.com/gemini-testing/hermione/blob/master/lib/browser/existing-browser.js#L74) с ошибкой типа `Error` и сообщением `Prepare screenshot failed with error type <some-type> and error message: <msg>`.

_JFYI_

2022-11-08 11:25 UTC, DudaGod reviewed
Еще не хватает документации. Т.е. предлагаю явно внутри assertView написать, что теперь он дожидается когда элемент появится. И для этого использует опции `waitTimeout` и `waitInterval`.

Кроме этого предлагаю увеличить `waitTimeout` до 3000 и `waitInterval` до 500 (такие дефолтные значения в wdio). Ну и написать, что эти опции вообще делают. Сейчас по доке в hermione вообще не очевидно, что они отвечают за ожидание пока элемент появится.

2022-11-08 11:25 UTC, DudaGod commented on lib/browser/commands/assert-view/index.js
> +        await Promise.map([].concat(selectors), selector => this.$(selector).then(el => el.waitForExist()));
Мы же можем сразу так писать - `browser.$(selector).waitForExist()`. Т.е. без `then`, ну и вместо `this` можно `browser` юзнуть как вариант.

2022-11-08 11:25 UTC, DudaGod commented on lib/browser/commands/assert-view/index.js
> +        await Promise.map([].concat(selectors), selector => this.$(selector).then(el => el.waitForExist()));
И следующий вопрос: какая ошибка и стектрейс будет в случае падения `waitForExist`? Судя по всему что-то такое- https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/waitForExist.ts#L52.  Спрашиваю к тому, что `waitForExist` принимает `timeoutMsg` и возможно правильно было бы дополнить ошибку самостоятельно. Скорей всего по стектрейсу будет не очень понятно, что проблема внутри `assertView`.

Еще кстати тут проблема может быть с тем, что пользователь сам добавит обертку над `assertView` и ему самостоятельно тоже придется дожидатся когда элемент появится. Тут ничего пока не предлагаю просто обращаю внимание.

2022-11-08 11:25 UTC, DudaGod commented on test/lib/browser/commands/assert-view/index.js
> +    it('should wait for element to exist', async () => {
Эти тесты должны быть по идее самыми первыми. Т.е. эта логика выполняется до вызова `assertView`. И я бы сначала проверял кейс с вызовом `assertView` на браузере и затем на элементе. Т.е. так же как мы делаем ниже.

2022-11-08 11:25 UTC, DudaGod commented on lib/browser/commands/assert-view/index.js
> +        await Promise.map([].concat(selectors), selector => this.$(selector).then(el => el.waitForExist()));
Не смотрел замедляет ли такая проверка время выполнения? Смотрю, что внутри `isExisting` используется вызов `browser.$$` - https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/isExisting.ts#L64-L65. Кажется, что она не очень быстро может работать в определенных кейсах.

2022-11-18 12:06 UTC, DudaGod commented on README.md
> +    await elem.assertView('plain'):
В конце `;`, а не `:`

2022-11-18 12:06 UTC, DudaGod commented on README.md
> +*Note: assertView will trigger waitForExist with [waitTimeout](#waittimeout) and [waitInterval](#waitinterval)*
Давай ссылку на команду `waitForExist` укажем - https://webdriver.io/docs/api/element/waitForExist/

Ну и предлагаю чуть подробнее описать опции `waitTimeout` и `waitInterval`. Сейчас вообще не понятно, что они делают. Писал про это ниже.

2022-11-21 11:49 UTC, DudaGod approved these changes
В остальном /ok

2022-11-21 11:49 UTC, DudaGod commented on README.md
> +*ex: `browser.$('.element').click()` will wait up to 3000ms for element to exist before clicking it by default*
`ex` - это типа `example`? Почему просто не написать - `For example: ...`? (кажется мы в доке обычно так и пишем)

2022-11-21 17:31 UTC, merged