fix: throw error on invalid reference
gemini-testing/hermione pull request #703
Opened 2022-12-15 12:59 UTC by KuznetsovRoman

2022-12-16 09:21 UTC, KuznetsovRoman reviewed
## Что сделано

Добавил проверку валидности у референса png. Без этого `html-report` валится и даже не отображает, что была какая-то ошибка.

2022-12-16 09:21 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/index.js
> +                    throw new Error(`element ("${selector}") still not existing after ${this.options.waitforTimeout} ms`);
Вот тут все таки лучше кидать `Error`, потому что:
1) `AssertViewError` по особому обрабатывается `html-reporter`-ом, так что тут в `html-report`е не будет показываться ни ошибка, ни стректрейс
2) Webdriverio в таком случае кидает именно Error
3) По стектрейсу все равно видно, что ошибка кинута внутри `assertView` и в сообщении ошибки можно увидеть селектор

Напомню, что тут ловится ошибка и кидается новая, потому что у `webdriverio` тут был непонятный стектрейс

2022-12-16 09:21 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/validator.js
> +const IEND = 0x49454e44;
I = 0x49, H = 0x48, D = 0x44, R = 0x55...

Типы чанков `png`

2022-12-16 09:21 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/validator.js
> +};
Быстрая функция, проверяющая "похож ли этот буфер на буфер png-изображения?"

Смотрит на [сигнатуру png](https://en.wikipedia.org/wiki/Portable_Network_Graphics#File_format) и проверяет, что первый чанк имеет тип - `IHDR`

2022-12-16 09:21 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/validator.js
> +exports.isValidPngBuffer = (buffer) => {
Еще возможно такое, что у картинки будет нормальный заголовок, но дальше она где-то обрывается, например, когда скачали не полностью. Чтобы такого не было, этой функцией проверяем:
1) наличие критических блоков `IDAT` и `IEND`
2) контрольные суммы блоков

> Почему написал свою функцию, вместо готовых решений?

У готовых решений 100% `precision`, но они тратят больше времени, так как помимо сверки контрольных сумм еще и валидируют каждый чанк, включая установленный тип сжатия, тип цвета и все такое.

То есть, теоретически такие ситуации, когда `isValidPngBuffer` выдаст ложноположительный результат имеются, но:
1) на практике возникнут только если специально постараться, чтоб они возникли
2) работает быстрее

2022-12-16 09:21 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/validator.js
> +    };
Наличие и порядок `IXHR` чанка проверяется в `isPngLike`. Помимо него, png должна иметь вот эти вот чанки.

2022-12-20 12:30 UTC, DudaGod requested changes
Не хватает тестов и хочется понять разницу во времени между твоим решением и готовым.

2022-12-20 12:30 UTC, DudaGod commented on lib/browser/commands/assert-view/validator.js
> +    if (buffer.length < 16 || buffer.readUInt32BE(12) !== IHDR) {
Я бы значения 12 используемое для сдвига в константу бы занес

2022-12-20 12:30 UTC, DudaGod commented on lib/browser/commands/assert-view/validator.js
> +exports.isValidPngBuffer = (buffer) => {
> У готовых решений 100% precision, но они тратят больше времени, так как помимо сверки контрольных сумм еще и валидируют каждый чанк, включая установленный тип сжатия, тип цвета и все такое.

А какая разница по времени между своим решением и использование готового? Если она минимальна, то и не зачем писать какой-то свой код и затем в будущем его поддерживать.

2022-12-20 12:30 UTC, DudaGod commented on lib/browser/commands/assert-view/validator.js
> +    for (let i = 8; i < buffer.byteLength;) {
Я бы `i` явно назвал - `offset`.

2022-12-20 12:30 UTC, DudaGod commented on lib/browser/commands/assert-view/validator.js
> +        if (length > buffer.byteLength - i - 8) {
Тут 8 не очень понятное число. На сколько я понимаю, ты тут специально смотришь на шаг вперед, т.е. должно быть 4 * 2. А 4 должно быть в понятной константе.

2022-12-20 12:30 UTC, DudaGod commented on lib/browser/commands/assert-view/validator.js
> +        const typeAndData = buffer.slice(i, i + 4 + length);
А зачем на `typeAndData`? Потому, что значения `type` попадает в итоговое `crc`?

2022-12-20 12:30 UTC, DudaGod commented on lib/browser/commands/assert-view/validator.js
> +    return !Object.values(essentialChunksSeen).includes(false);
Не очень простой алгоритм получился конечно. Хочется услышать сколько он времени нам будет экономить по сравнению с готовыми решениями.

2022-12-20 12:30 UTC, DudaGod commented on lib/browser/commands/assert-view/validator.js
> +    return !Object.values(essentialChunksSeen).includes(false);
Ну и тестов на этот файл не вижу

2022-12-20 21:43 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/index.js
> +            throw new InvalidPngError(`Reference ${refImg.path} is not a valid png`);
> Не думал еще предложить возможные варианты решения? Например переснять скриншот или выполнить `git lfs pull` если используется `git lfs`

Предлагаешь также проверять "Является ли файл `git lfs` указателем"?

2022-12-20 21:52 UTC, dicrtarasov commented
Мне кажется что не нужно реализовать лишние функции. Авто должно ехать, а выпечкой хлеба (git lfs) пусть занимается git-lfs.

Испорчен файл эталона - не тот что снят в тесте, а тот с которым сравнивается.

Файл может быть испорчен не только lfs, но и неважно каким другим способом. Нужно обработать общую ситуацию когда файл изображения испорчен.

В качестве подходящего и простого решения - можно выдать в лог сообщение с указанием пути файла и дальше пройти по тому пути алгоритма, как будто файл не существует (reference not found).

В прежней версии выдавалась ошибка с указанием пути файла и тест исключался из отчёта.

В последней версии выдаётся ошибка БЕЗ указания имени файла, что совсем-совсем плохо, так как нужно использовать дополнительный софт, чтобы отыскать битый файл.

2022-12-20 22:01 UTC, dicrtarasov commented
Возможные способы порчи файл:
- lfs
- отключение питания с собой инфры
- не докачан при обрыве сети
- формат испорчен или не распознан после софта оптимизации изображений
... и многие другие.

Поэтому не нужно:
- проверять сигнатуру PNG,;
- пытаться искать LFS 
- другим способом пытаться восстановить битый файл.

Но очень  важно:
- выдать в сообщении путь файла, на утром произошла ошибка при открытии;
- включить тест, которому принадлежит файл в отчёт без картинки, как будто эталон не существует.

2022-12-20 22:05 UTC, KuznetsovRoman commented
> Поэтому не нужно:
> 
> * проверять сигнатуру PNG,;

Это одна из проверок на PNG-шность, без этого никак.

2022-12-20 22:07 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/validator.js
> +        const typeAndData = buffer.slice(i, i + 4 + length);
> Потому, что значения `type` попадает в итоговое `crc`?

Да

2022-12-20 22:13 UTC, dicrtarasov commented
> > Поэтому не нужно:
> > 
> > * проверять сигнатуру PNG,;
> 
> Это одна из проверок на PNG-шность, без этого никак.

А 'html-reporter' точно является пакетом обработки форматов изображений или он все же использует для этого в зависимостях специализированные библиотеки, которые лучше умеют распознавать графические файлы?

А 'html-report' точно знаком со всеми существующими и будущими форматами png и их сигнатурами?

Мне кажется что будет гораздо лучше, если html-report сможет создавать правильные html-отчеты без пропуска тестов. Это более важная задача этого пакета, чем разбираться в форматах изображений.

2022-12-20 22:16 UTC, KuznetsovRoman commented
> Мне кажется что будет гораздо лучше, если html-report сможет создавать правильные html-отчеты без пропуска тестов.

Вот именно над этой issue и ведется работа в этом пулл реквесте

2022-12-21 10:43 UTC, DudaGod commented on lib/browser/commands/assert-view/index.js
> +            throw new InvalidPngError(`Reference ${refImg.path} is not a valid png`);
> Предлагаешь также проверять "Является ли файл git lfs указателем"?

Нет. Я подумал можем ли мы тут как-то помочь пользователю. Т.е. мы тут сообщаем о проблеме - "невалидный эталон", но не говорим пользователю что ему с этим делать. Я бы наверное добавил к ошибке - `Try to reaccept the reference image`. Но если предположить, что пользователь использует `git lfs` и у него скриншоты пока находятся в виде указателей, то он так пол дня будет все скриншоты переснимать вместо того , чтобы выполнить `git lfs pull`.

Предлагаю пока тут оставить как есть.

2022-12-21 10:44 UTC, DudaGod commented on lib/browser/commands/assert-view/validator.js
> +exports.isValidPngBuffer = (buffer) => {
> А какая разница по времени между своим решением и использование готового? Если она минимальна, то и не зачем писать какой-то свой код и затем в будущем его поддерживать.

Вот на это не ответил. И пришли пожалуйста ссылку на пакет, про который ты говорил выше.

2022-12-21 11:06 UTC, DudaGod commented
> Мне кажется что не нужно реализовать лишние функции. Авто должно ехать, а выпечкой хлеба (git lfs) пусть занимается git-lfs.

Никто лишние функции и не добавляет.

> Испорчен файл эталона - не тот что снят в тесте, а тот с которым сравнивается.

Чего? ) Эталон - это изображение, которое изначально было изображением снятым в процессе выполнения теста. И только потом пользователь его явно заацептил и оно стало эталоном. Проблема возникает именно в эталонах и ее мы здесь исправляем.

> Файл может быть испорчен не только lfs, но и неважно каким другим способом. Нужно обработать общую ситуацию когда файл изображения испорчен.

А кто говорит, что эталон может быть некорректным только из-за lfs? Мы знаем, что существуют и другие способы и все они будут учтены.

> В прежней версии выдавалась ошибка с указанием пути файла и тест исключался из отчёта.

Из отчета ничего не исключалось. Упавший тест помечался сфейлленым.

В последней версии выдаётся ошибка БЕЗ указания имени файла, что совсем-совсем плохо, так как нужно использовать дополнительный софт, чтобы отыскать битый файл.

Да, мы в курсе этой проблемы, так как ты завел issue - https://github.com/gemini-testing/html-reporter/issues/436. После влития этого PR-а и выпуска новой версии в ошибке будет содержаться путь до битого скриншота. Т.е. будет точно такое же поведение как и раньше.

> Возможные способы порчи файл: ...

Спасибо. О всех этих способах мы знаем.

> Поэтому не нужно:
проверять сигнатуру PNG,;

Почему не нужно?

> Поэтому не нужно:
пытаться искать LFS

Этим никто и не собирался заниматься.

> Поэтому не нужно:
другим способом пытаться восстановить битый файл.

Воскрешать битые файлы тоже не собирались.

> Но очень важно:
выдать в сообщении путь файла, на утром произошла ошибка при открытии;

Не переживай, после этого PR-а путь к эталону будет присутствовать в ошибке.

> Но очень важно:
включить тест, которому принадлежит файл в отчёт без картинки, как будто эталон не существует.

Что значит включить тест? Судя по описанию ты имеешь в виду кейс который ты встретил в issue - https://github.com/gemini-testing/html-reporter/issues/436, что у тебя в отчете не было информации о упавшем тесте. Проблема не в том, что мы тест выключили, а в том что html-reporter сфейлился и не успел данные о упавших тестах добавить в sqlite базку и соответственно отобразить их в отчете.

Итого: не понимаю зачем столько текста. Проблема понятна и как ее решить мы знаем. Для пользователей поведение будет точно такое же как и раньше.

2022-12-21 11:08 UTC, KuznetsovRoman commented on lib/browser/commands/assert-view/validator.js
> +exports.isValidPngBuffer = (buffer) => {
https://www.npmjs.com/package/png-validator

2022-12-21 11:38 UTC, dicrtarasov commented
Изначально проблема была замечена в том, что в json-отчете мы видим что один тест failed, а в html-отчете все success зелёное. Это создало большую проблему, так как упавший тест мы не заметили в процессе решила, так как в html-отчете все Ok.

Я начал разбираться что и почему так. И выяснил, что у теста был испорчен файл эталона и при формировании html-отчета этот тест был исключен (не попал в отчёт).

Подробно эту ситуацию я описывал в другом bugreport, не в этом треде. К сожалению сам отчёт приложить не могу, но приложил скрины, на которых детально была показана ситуация.

2022-12-21 11:41 UTC, dicrtarasov commented
В sql-базу сфэйленый тест наверное попал, так как в json-report он отобразился. Поэтому для решения проблемы пришлось откатывать назад версию html-report.

2023-01-11 09:15 UTC, DudaGod commented
> Изначально проблема была замечена в том, что в json-отчете мы видим что один тест failed, а в html-отчете все success зелёное. Это создало большую проблему, так как упавший тест мы не заметили в процессе релиза, так как в html-отчете все Ok.
Я начал разбираться что и почему так. И выяснил, что у теста был испорчен файл эталона и при формировании html-отчета этот тест был исключен (не попал в отчёт).

Там проблема была с тем, что создание html-отчета сфейлилось по дороге и информация о тесте не успела записаться в sqlite базку. В итоге по html-отчету казалось, что упавших тестов нет. Но отдельный плагин формирующий json-отчет эту информацию получить успел и соответственно отобразил ее.

2023-01-11 09:21 UTC, DudaGod approved these changes
🔥

2023-01-11 09:21 UTC, DudaGod commented on lib/browser/commands/assert-view/index.js
> +                    throw new Error(`element ("${selector}") still not existing after ${this.options.waitforTimeout} ms`);
Это можно было отдельным коммитом пофиксить. Чтобы потом в changelog и release notes отобразить, что такую проблему тоже поправили. А не только разрулили кейс с `invalid reference`.

2023-01-11 09:21 UTC, DudaGod commented on test/lib/browser/commands/assert-view/index.js
> +        return assert.isRejected(browser.publicAPI.assertView('plain', '.selector'), InvalidPngError);
А зачем тут `return`? Можно же просто `await` юзнуть.

2023-01-11 18:03 UTC, merged