feat: add ability to write test steps
gemini-testing/hermione pull request #715
Opened 2023-01-25 00:11 UTC by KuznetsovRoman

2023-01-25 00:50 UTC, KuznetsovRoman reviewed
## Что сделано:
- Добавил группировку `init`, `beforeEach`, `afterEach` в `history`
- Добавил возможность писать степы, чтобы `history` в `html-report`-е была понятнее

### Как писать степы:

```ts
it('test', ({browser}) => {
    await browser.runStep('Название шага', async () => {
        ... содержимое шага ...
        await browser.runStep('Название вложенного шага', async () => {
            ... содержимое вложенного шага ...
        });
    });
    await browser.runStep('Какой-то клик', () => browser.$('.elem').click());
})
```

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/browser/browser.js
> +    }
Этот метод заворачивает содержимое в одну команду в истории. Заходит в коллстэк, выполняет функцию, и выходит из коллстэка.

Нужен для разметки beforeEach(), afterEach(), init(), resetCursor() в истории.

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/browser/browser.js
> +    }
Этот метод модифицирует коллстэк, добавляя в него пометку на текущую команду и ее предков (начинает с предков)

1. Вызываем этот метод, когда выбрасывается исключение
2. В html-reporter-е получаем `history` с пометками, какая(/-ие) команды привели к падению теста
3. Раскрываем упавшие группы / команду

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/browser/commands/runStep.js
> +    session.addCommand('runStep', runStep);
Добавляем какую-то команду к браузеру, чтобы в истории было видно, что команды были запущены внутри этой.

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/browser/existing-browser.js
> +        });
Добавляем `init()` в `history`.

- скрываем команды, выполняемые в `_prepareSession`, `_performCalibration` в один степ, чтобы не мешались
- как бонус, получаем информацию о времени выполнения этих трех команд

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/browser/history/callstack.js
> +    }
- Всегда помечаем как упавшую верхнюю команду / сьют
- Углубляемся внутрь, помечая потомков, пока `shouldPropagate` возвращает `true`

`shouldPropagate` описан в `./index.js` и работает так, что:
- помечаются все родительские группы (`runStep`, `beforeEach`, `afterEach`, `init`) упавшей команды
- помечается упавшая команда, вызванная пользователем (ее потомки - нет)

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/browser/history/utils.js
> +exports.isGroup = node => isStep(node) || isHook(node) || isInit(node);
Вот эти вот 4 типа нод образуют группы, которые упоминались выше

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/browser/new-browser.js
> +        }
в `new-browser` `init` выполняется при необходимости

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/config/browser-options.js
> +                const availableValues = [false, saveHistory.FAILED, saveHistory.ALL, true];
- `false` - запись истории отключена
- `failed` - история передается html-reporter-у для последующей записи в базу только для упавших тестов
- `all` - запись истории включена
- `true` - то же самое, что и `all`

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/worker/runner/test-runner/index.js
> +                }
Заворачиваем команды от resetCursor в отдельный степ

2023-01-25 00:50 UTC, KuznetsovRoman commented on lib/worker/runner/test-runner/index.js
> +        }
Передаем историю только если она либо включена для всех тестов, либо только для упавших и текущий тест упал

2023-01-25 00:50 UTC, KuznetsovRoman commented on test/lib/browser/history/index.js
> +                            assert.isTrue(getBrowser().flushHistory().every(node => node.n !== commandName));
Теперь проверяем не то, что история должна быть пустой, а то, что там не должно быть такой команды, потому что `init()` туда пишется

2023-01-26 11:22 UTC, xrsd requested changes

2023-01-26 11:22 UTC, xrsd commented on lib/worker/runner/test-runner/index.js
> +            const beforeEach = async () => {
Меня смущают здесь несколько вещей:
1. Название `hasBeforeEach` не совсем коррелирует с наличием опции `resetCursor`, а, кажется, что имеет отношение только ко второй части выражения – `hookRunner.hasBeforeEachHooks()`. Поэтому я бы, скорее, назвал бы этот флаг `needsBeforeEachStep`.
2. Чисто формально, ты создаешь функцию `beforeEach`, которая, возможно, тебе и не понадобится вовсе, к тому же доступную во всем скоупе функции `run`, хотя она нужна только внутри условия. Если бы ты пользовался ею еще где-то ниже, то было бы норм, чтобы избавиться от дублирования и повысить читаемость. Хотя да, ты выигрываешь 2 отступа. В этом есть плюс.
3. Почему еще название `hasBeforeEach` не очень, потому что `hookRunner.hasBeforeEachHooks()` может вернуть `false`, но мы, тем не менее, будем иметь `hasBeforeEach = true`, если `resetCursor == true`, и всё равно вызовем `hookRunner.runBeforeEachHooks()`, хотя этих хуков может не быть.

Поэтому я вижу этот код немного по-другому:

```js
const {resetCursor} = browser.config;
const needsBeforeEachStep = resetCursor || hookRunner.hasBeforeEachHooks();

if (needsBeforeEachStep) {
    await browser.runWithHistory('beforeEach', async () => {
        if (resetCursor) {
            // TODO: make it on browser.init when "actions" method will be implemented in all webdrivers
            await browser.runWithHistory('resetCursor', () => this._resetCursorPosition(browser));
        }

        await hookRunner.runBeforeEachHooks();
    });
}
```

2023-01-26 11:22 UTC, xrsd commented on lib/worker/runner/test-runner/index.js
> +            const hasAfterEach = hookRunner.hasAfterEachHooks();
Если выше переименовывать `hasBeforeEach` в `needsBeforeEachStep`, то здесь надо тоже переименовать в `needsAfterEachStep` для консистентности.

2023-01-26 11:22 UTC, xrsd commented on lib/worker/runner/test-runner/index.js
> +        const history = browser.flushHistory();
Вроде не ты это название придумывал, но `flush` – не самое удачное название для метода. Потому что, как правило, `flush`-методы ничего не возвращают. Они скидывают что-то куда-то, обнуляют содержимое (кэша, например), но при этом ничего не возвращают.

2023-01-26 11:27 UTC, KuznetsovRoman commented on lib/browser/browser.js
> +    runWithHistory(commandName, fn) {
> функция называется `runWithHistory`, но в то же время под капотом `withHistory` или `withoutHistory`

Так у нас же все так работает. Есть метод браузера `addHistory`, но он может и не добавить - в зависимости от конфига

Есть метод браузера `flushHistory`, но он может и не флашить `history` - в зависимости от конфига

2023-01-26 11:29 UTC, xrsd commented on lib/worker/runner/test-runner/index.js
> +            const beforeEach = async () => {
> к тому же доступную во всем скоупе функции `run`, хотя она нужна только внутри условия.

Тут я, наверное, не прав, так как видимость будет ограничена блоком `try`.

2023-01-26 11:32 UTC, KuznetsovRoman commented on lib/browser/browser.js
> +    runWithHistory(commandName, fn) {
>Не очень очевидно, что функция асинхронная

Она и ничего асинхронного не делает. Просто запускает функцию, которую ты в нее передашь. Если переданная функция асинхронная, то да, возвращается промис, который и ждем. У нас так же `lib/browser/history/runWithHooks` работает.

2023-01-26 11:56 UTC, KuznetsovRoman commented on lib/browser/history/utils.js
> +exports.isGroup = node => isStep(node) || isHook(node) || isInit(node);
`beforeEach`, `afterEach` - разные типы нод, хоть и оба являются хуками

2023-01-29 18:31 UTC, KuznetsovRoman commented on lib/browser/browser.js
> +    markError() {
-> `markHistoryError`

2023-01-29 18:42 UTC, KuznetsovRoman commented on lib/worker/runner/test-runner/index.js
> +        const history = browser.flushHistory();
-> `releaseHistory`

2023-01-30 07:33 UTC, xrsd commented on test/lib/browser/new-browser.js
>          it('should return an empty array if it if off', async () => {
`if it is off`?

2023-01-30 07:34 UTC, xrsd commented on test/lib/worker/runner/test-runner/index.js
> +            it('should log "beforeEach" in history if beforeEach hooks are exist', async () => {
`exist` – `are` не нужно

2023-01-30 07:35 UTC, xrsd commented on test/lib/worker/runner/test-runner/index.js
> +            it('should not log "beforeEach" in history if beforeEach hooks are not exist', async () => {
`do not exist`

2023-01-30 07:35 UTC, xrsd commented on test/lib/worker/runner/test-runner/index.js
> +            it('should log "afterEach" in history if afterEach hooks are exist', async () => {
`exist`, `are` – не нужно

2023-01-30 07:35 UTC, xrsd commented on test/lib/worker/runner/test-runner/index.js
> +            it('should not log "afterEach" in history if afterEach hooks are not exist', async () => {
`do not exist`

2023-01-30 07:36 UTC, xrsd approved these changes

2023-01-30 10:21 UTC, merged

2023-01-30 12:41 UTC, DudaGod reviewed
Не все досмотрел. Но вопросов достаточно.

2023-01-30 12:41 UTC, DudaGod commented on lib/browser/history/callstack.js
> +        let shouldContinue = !!currentNode;
Вместо такой записи рекомендуется использовать `Boolean`, оно сильно понятнее.

2023-01-30 12:41 UTC, DudaGod commented on lib/worker/runner/test-runner/index.js
> +            browser.markHistoryError();
Зачем второй вызов? Ну и я все еще считаю, что это плохое API.

2023-01-30 12:41 UTC, DudaGod commented on lib/worker/runner/test-runner/index.js
> +            const needsAfterEach = hookRunner.hasAfterEachHooks();
А зачем так? Почему вызов `hookRunner.runAfterEachHooks()` нельзя просто в `runStep` обернуть?

2023-01-30 12:41 UTC, DudaGod commented on lib/worker/runner/test-runner/index.js
> +                        await browser.runWithHistory('resetCursor', () => this._resetCursorPosition(browser));
А зачем отдельно `resetCursor` выносить не понял?

2023-01-30 12:41 UTC, DudaGod commented on lib/worker/runner/test-runner/index.js
> +            if (needsBeforeEach) {
Тоже не пойму зачем так делать? Почему просто не вызвать `addStep('...', hook())` ?

2023-01-30 12:41 UTC, DudaGod commented on lib/browser/browser.js
> +    markHistoryError() {
Тут тоже странное API. Я правильно понимаю, что если в `history` нужно будет еще 10 методов, то мы их просто с примерно таким же названием создаем внутри браузера, который просто вызывает такие же методы у history, верно?

2023-01-30 12:41 UTC, DudaGod commented on lib/browser/history/utils.js
> +    FAILED: 'f',
А почему не `IS_FAILED`?

Эти данные потребляет плагин `hermione-profiler`. Не смотрел как он с новыми данными будет работать (по идее проблем быть не должно)? Но возможно стоит поддержать в нем эту инфу в будущем.

2023-01-30 12:41 UTC, DudaGod commented on lib/browser/commands/runStep.js
> +        return stepCb();
А почему просто не `await`-ить и не сделать функцию явно асинхронной? Ведь ее `return` никак не обрабатывается. Ну и почему ее сразу же внутри `addCommand` не описать?

2023-01-30 12:41 UTC, DudaGod commented on lib/browser/browser.js
> +            ? history.runWithHistory(this._callstackHistory, commandName, fn)
`afterEach`, `beforeEach` и т.д. это же не команды браузера

2023-01-30 12:44 UTC, KuznetsovRoman commented on README.md
> +*Note: [html-reporter](https://github.com/gemini-testing/html-reporter) v9.7.6+ highly recommended.*
Работает. Но отображается лучше с 9.7.6+

2023-01-30 12:48 UTC, KuznetsovRoman commented on README.md
> +- some step name
Он не обязательный.

2023-01-30 12:50 UTC, KuznetsovRoman commented on README.md
> +### RunStep
> Почему `runStep`

Так решили 18.01 в 15:00

2023-01-30 12:54 UTC, KuznetsovRoman commented on README.md
> +Will produce the following history, if test fails on 'Can't call click on element with selector "not-exist" because element wasn't found':
> Это должно быть в history

Отдельного блока про `history` в доке нет. 

> Зачем тут еще про ошибки рассказывать?

Хотел показать пример со вложенными степами. На пройденном тесте было бы неясно, зачем вообще использовать эти вложенные степы

2023-01-30 12:58 UTC, KuznetsovRoman commented on README.md
> + - `'onlyFailed'` - history is saved for failed tests only
20.01 15:11
Не хочется ради этого отрывать обратную совместимость
Не понял, почему `saveHistory` подразумевает `boolean`

2023-01-30 13:01 UTC, KuznetsovRoman commented on lib/worker/runner/test-runner/index.js
> +            browser.markHistoryError();
После падения в beforeEach или body теста, afterEach все равно запустится. По итогу тест может упасть дважды: в body, и в afterEach. Соответственно, ошибки две, пометить нужно два раза

2023-01-30 13:03 UTC, KuznetsovRoman commented on lib/worker/runner/test-runner/index.js
> +                        await browser.runWithHistory('resetCursor', () => this._resetCursorPosition(browser));
Потому что без этого в истории будет несколько команд, которые непонятно откуда идут. `$('body')`,  `scrollIntoView`...

2023-01-30 13:03 UTC, KuznetsovRoman commented on lib/worker/runner/test-runner/index.js
> +            if (needsBeforeEach) {
Потому что этого `afterEach` может и не быть. Не хочется добавлять в историю пустую команду

2023-01-30 13:06 UTC, KuznetsovRoman commented on lib/browser/browser.js
> +    markHistoryError() {
Какие еще методы могут понадобиться в `history`?

По сути нет другого способа обратиться к необходимой истории находясь внутри `test-runner`, который как раз связывает браузер с тестом.

А обратиться к истории нужно чтобы пометить ошибку.

2023-01-30 14:08 UTC, DudaGod commented on README.md
> +*Note: [html-reporter](https://github.com/gemini-testing/html-reporter) v9.7.6+ highly recommended.*
Так может так и написать, что с версией 9.7.6 отображение лучше?

2023-01-30 14:08 UTC, DudaGod commented on README.md
> + - `'onlyFailed'` - history is saved for failed tests only
Так я же предложил вариант без отрыва обратной совместимости. Плюс у нас сейчас все равно еще один мажор поедет Поэтому можно опцию назвать как хочешь. Я бы назвал понятнее. По названию `saveHistory` или `saveSomething` я ожидаю варианты ответов `true` или `false`. Ну и как по мне опции понятнее когда они получают одинаковый тип аргументов, а не сборную солянку.

2023-01-30 14:08 UTC, DudaGod commented on lib/browser/browser.js
> +    markHistoryError() {
> Какие еще методы могут понадобиться в history?

Да любые. Например смерджить истории всех тестов, которые исполнялись в одной браузерной сессии.

> По сути нет другого способа обратиться к необходимой истории находясь внутри test-runner, который как раз связывает браузер с тестом.

Так можно же сделать изменения, которые это позволят сделать. Сейчас же получается, что история - это уже не совсем история вызова браузерных команд. Это больше история выполнения самого теста. Потому что теперь мы в нее добавляем информацию о хуках, пользовательских описаниях команды и можем it добавить например и т.д. Возможно эта история и не должна быть теперь в браузере?

2023-01-30 19:12 UTC, KuznetsovRoman commented on README.md
> +- some step name
> Он же всегда выполняется, если история включена

В new-browser не всегда

2023-01-31 10:44 UTC, DudaGod commented on README.md
> +- some step name
> В new-browser не всегда

А зачем пользователю про `new-browser` вообще что-то показывать? Он же запускается только при старте браузерной сессии в которой может выполнится N тестов. Т.е. как это вообще относится к истории выполнения теста?

2023-03-03 05:01 UTC, KuznetsovRoman commented on lib/browser/browser.js
> +    markHistoryError() {
> Возможно эта история и не должна быть теперь в браузере?

Имеем:
- Эта история должна подключаться в init, причем после того, как подключились к сессии, и перед всем остальным (добавление команд, подготовка сессии, калибровка...)
- Эта история работает как перезапись команд
- Команды-обертки обращаются к вполне конкретному коллстэку.
- Заворачиваем команды мы один раз за сессию, перед тем, как добавить новые

Соответственно, коллстэк один на сессию, и создавать его нужно именно внутри `init` (а есть еще `reinit` и только `browser-pool` знает между ними разницу)

Могу убрать все эти "исторические" методы из браузера, чтобы не беспокоили, и доставать историю из браузера в тест-раннере.

Либо нужно завести какую-то глобальную мапку [sessionId] -> history, для которой еще нужно подумать, как бы получать уведомления о завершении сессии.

2023-03-03 05:11 UTC, KuznetsovRoman commented on lib/browser/commands/runStep.js
> +        return stepCb();
> почему просто не `await`-ить и не сделать функцию явно асинхронной?

А зачем? Что это дает? Эта функция даже не всегда будет асинхронной.

> ее return никак не `обрабатывается`

Что имеется ввиду? Это зависит от того, кто использует эту функцию. Может он захочет создать степ "спарсить страничку" и вернуть результат в этом степе одной строчкой как-то типа

`const result = await browser.runStep('parse', async () => { ...`

2023-03-03 05:28 UTC, KuznetsovRoman commented on README.md
> +- some step name
Я имел ввиду, что в `new-browser` этот `init` был только если в конфиге установлен `pageLoadTimeout`.

В правках такой `init` будет всегда, для консистентности

2023-03-03 09:38 UTC, DudaGod commented on lib/browser/browser.js
> +    markHistoryError() {
Я предлагаю подумать в сторону реализации подхода с эмитом событий о вызываемых командах/хуках/степах/... В wdio есть похожие события - https://webdriver.io/docs/configuration/#beforecommand. За счет таких событий мы сможем в разных плагинах как угодно потреблять эту информацию. Например в `html-reporter` сможем построить подробную историю выполнения теста. А в режиме gui даже появится возможность отображать текущую выполняемую команду в рантайме.