feat: add logs timestamp
gemini-testing/hermione pull request #727
Opened 2023-02-28 07:25 UTC by c1825846

Добавил метку времени без локали перед выводом в консоль, добавил тесты

2023-02-28 08:23 UTC, KuznetsovRoman commented on test/lib/utils/logger.js
> +        assert.match(consoleLog.getCall(0).args[0], /^\[.*] message$/);
> should start with timestamp message

Тест проверяет, что перед сообщением есть квадратные скобки, в которых возможно что-то есть, а не то, что там именно временная метка

> assert.match(consoleLog.getCall(0).args[0], ...)

Лучше писать это через `calledOnceWith`, посмотри примеры использования поиском по репозиторию

2023-02-28 10:36 UTC, KuznetsovRoman commented on test/lib/utils/logger.js
> +        const {log} = require('lib/utils/logger');
Все еще не нравится такой `require`: обычно они все у нас в шапке файла лежат.

И сам логгер мы обычно реквайрим целиком:

```js
'use strict';

const logger = require('lib/utils/logger');
```

```js
logger.log('message');
```

2023-02-28 14:16 UTC, c1825846 commented on test/lib/utils/logger.js
> +        const {log} = require('lib/utils/logger');
можно вынести `require`  в шапку, но и sinon.spy тоже в шапку пойдёт, либо в describe всё это. как лучше сделать?

2023-03-01 15:38 UTC, xrsd commented on test/lib/utils/logger.js
> +    });
Второй раз в том же формате проверять тест не обязательно, до этого я приводил это как пример, чтобы убедиться, что стабы работают. Но вот, что можно проверить, это что будет если передать в log-функцию 2 аргумента:
```js
logger.log('another message', 'with additional argument');
```

2023-03-01 15:45 UTC, xrsd commented on test/lib/utils/logger.js
> +    const clock = sinon.useFakeTimers();
Нужно перенести в `beforeEach`, иначе у тебя в `afterEach` произойдет `restore` и для других тестов фейка таймеров уже не будет.

2023-03-01 15:45 UTC, xrsd commented on test/lib/utils/logger.js
> +describe.only('log', () => {
`only` забыл убрать

2023-03-01 16:12 UTC, xrsd approved these changes

2023-03-02 09:25 UTC, DudaGod requested changes
Можно чуть проще реализовать и тестов не хватает для `warn` и `error`

2023-03-02 09:25 UTC, DudaGod commented on lib/utils/logger.js
> +    const firstArgWithTimestamp = util.format(`[${timestamp}]`, firstArg);
А я что-то не понял. Для чего нам тут `util.format`? Описание метода - https://nodejs.org/api/util.html#utilformatformat-args. Мы же ничего тут не форматируем. У нас первый аргумент обычная строка. Т.е. можно `firstArg` вообще не получать. И вызывать метод следующим образом:
```
console[logFnName](timestamp, ...restArgs);
```

2023-03-02 09:25 UTC, DudaGod commented on test/lib/utils/logger.js
> +describe('log', () => {
Я бы describe именовал как `utils/logger`

2023-03-02 09:25 UTC, DudaGod commented on test/lib/utils/logger.js
> +        sandbox.stub(console, 'log');
А где стабы для `warn` и `error`?

2023-03-02 09:25 UTC, DudaGod commented on test/lib/utils/logger.js
> +    it('should start with timestamp message', () => {
Тут не хватает проверок для всех видов логов: `warn` и `error`.
Но так как тесты будут абсолютно идентичны, то можно через `forEach` их сгенерить:
```
['log', 'warn', 'error'].forEach((method) => {
  describe(method, () => {
    it(..., () => {});
  });
});
```

2023-03-02 09:25 UTC, DudaGod commented on test/lib/utils/logger.js
> +        const date = format(new Date(), 'HH:mm:ss OO');
А почему бы тут не использовать явно захардкоженную дату? Чтобы ниже assert явно указать как это дата преобразуется. Т.е. чтобы в assert мы писали типа `'12:00:00 GMT+3'. Тогда тест будет намного понятнее и правильнее. Т.е. он защитит от случайного изменения формата с `HH:mm:ss OO` на `ss:mm:HH` например. А текущий тест от этого никак не защищает.

2023-03-02 09:25 UTC, DudaGod commented on test/lib/utils/logger.js
> +    it('should start with timestamp only first argument', () => {
Этот тест кажется вообще не нужный если использовать правки о которых я выше написал. Тогда можно просто один `it` написать с несколькими аргументами от юзера.

2023-03-02 10:18 UTC, xrsd requested changes

2023-03-02 10:18 UTC, xrsd commented on test/lib/utils/logger.js
> +        clock = sinon.useFakeTimers();
Надо явно задать фейковое время:

```js
clock = sinon.useFakeTimers({
   now: 1677661200000
});
```

Например, это соответствует `12:00:00 GMT+3`.

2023-03-02 10:19 UTC, xrsd commented on test/lib/utils/logger.js
> +                assert.calledOnceWith(console[logFnName], '[03:00:00 GMT+3]', 'message', 'another message');
Иначе без настройки фейка времени здесь не очевидно, откуда взялось `03:00:00 GMT+3`

2023-03-02 10:20 UTC, xrsd commented on test/lib/utils/logger.js
> +                assert.calledOnceWith(console[logFnName], '[03:00:00 GMT+3]', 'message', 'another message');
Ну и возможно есть смысл перенести ближе к тесту настройку времени

2023-03-02 11:35 UTC, xrsd commented on test/lib/utils/logger.js
> +            });
```js
describe('hooks', function() {
    before(function() {
        // runs before all tests in this file regardless where this line is defined.
    });

    after(function() {
        // runs after all tests in this file
    });

    beforeEach(function() {
        // runs before each test in this block
    });

    afterEach(function() {
        // runs after each test in this block
    });

    // test cases
});
```

У тебя получилась хрупкая конструкция. Если ты добавишь, например, еще 1 тест в свой `describe(logFnName...`, то он упадет, потому что `before` срабатывает 1 раз перед тем как запустить тесты внутри `describe`, а `afterEach` выше срабатывает постоянно для всех тестов. И у тебя после первого же теста фейк таймеров отменится и `spy` тоже.

2023-03-02 11:36 UTC, xrsd commented on test/lib/utils/logger.js
> +            });
Надо заменить `before` на `beforeEach` и занести `afterEach` внутрь `describe(logFnName...`

2023-03-02 13:00 UTC, xrsd approved these changes

2023-03-03 13:33 UTC, DudaGod approved these changes

2023-03-03 13:34 UTC, DudaGod commented
Перед влитием нужно разрезолвить конфликты и убедится, что тесты в CI проходят

2023-03-06 09:59 UTC, xrsd commented on test/lib/utils/logger.js
> +                process.env = originalEnv;
Так работать не будет. У тебя ссылка копируется выше в `originalEnv`.

2023-03-06 10:07 UTC, merged