docs: simplify quick start
gemini-testing/hermione pull request #753
Opened 2023-03-31 21:27 UTC by DudaGod

2023-04-03 09:40 UTC, xrsd requested changes

2023-04-03 09:40 UTC, xrsd commented on README.md
> +You need just run cli command from [create-hermione-app](https://github.com/gemini-testing/create-hermione-app) tool and answer on few questions:
правильно: `You just need to run the cli command` ... `and answer a few questions`.

2023-04-03 09:40 UTC, xrsd commented on README.md
> +### Fast way with using cli command
Я бы по-другому заголовки назвал:
- `Using create-hermione-app (a quick way)`
- `Configuring .hermione.conf.js by yourself (a slow way)`

2023-04-03 09:40 UTC, xrsd commented on README.md
> +Create hermione config file with name `.hermione.conf.js` in the project root. There are two configuration options depending on the method selected in the `prerequisites` block.
лучше [section](https://translate.yandex.ru/?source_lang=en&target_lang=ru&text=section) вместо [block](https://translate.yandex.ru/?source_lang=en&target_lang=ru&text=block)

2023-04-03 09:50 UTC, xrsd commented on README.md
> +Now we have two ways how to configure project.
Если мы ниже говорим `by yourself`, то тогда надо бы здесь говорить: `Now you have two ways...`

2023-04-13 13:44 UTC, DudaGod commented on README.md
> +Now we have two ways how to configure project.
А зачем `projects` в множественном писать?

2023-04-13 13:51 UTC, xrsd commented on README.md
> +Now we have two ways how to configure project.
А, да это я опечатался. Единственное число норм.

2023-04-13 15:46 UTC, xrsd commented on README.md
> +  - [Slow way with self-tuning](#slow-way-with-self-tuning)
А содержание переделать?

2023-04-13 15:47 UTC, xrsd commented on README.md
> +You just need run cli command from [create-hermione-app](https://github.com/gemini-testing/create-hermione-app) tool and answer a few questions:
`to run the`

2023-04-13 15:48 UTC, xrsd approved these changes

2023-04-14 08:32 UTC, sipayRT approved these changes

2023-04-14 08:32 UTC, sipayRT commented on README.md
> +npm init hermione-app YOUR_PROJECT_NAME
это не имя проекта, а путь к нему

можно и показать опцию `-y`

2023-05-22 12:41 UTC, merged