feat: speedup of test environment initialisation
gemini-testing/hermione pull request #769
Opened 2023-06-28 13:30 UTC by rprovodenko

2023-07-03 11:23 UTC, rprovodenko commented on README.md
> +- [Hermione](#hermione)
автоформат

2023-07-04 09:56 UTC, DudaGod requested changes
На новую логику тестов не хватает

2023-07-04 09:56 UTC, DudaGod commented on src/browser/existing-browser.js
> +        await this._session.switchToWindow(newWindow);
А для чего теперь вот этот код выполнять (вопрос про `getWindowsHandles` и `switchToWindow`? Ты же выше вроде бы закрываешь старые браузерные инстансы/контексты выше и в итоге у нас один window болтается.

2023-07-04 09:56 UTC, DudaGod commented on src/browser/existing-browser.js
> +                    await context.close();
А для чего контекст явно закрывать? Разве он не завершится автоматически при выполнении `page.close()`?

2023-07-04 11:01 UTC, rprovodenko commented on src/browser/existing-browser.js
> +    async _cycleBrowserContext() {
cycle означает сменить со старого на новый, по-русски "цикл" или "циклировать"

2023-07-04 11:02 UTC, rprovodenko commented on src/browser/existing-browser.js
> +        await this._session.switchToWindow(newWindow);
потому что вибдрайверу нужно иметь активное окно. просто закрытием других вкладок неактивное окно не становится активным

2023-07-04 11:02 UTC, rprovodenko commented on src/browser/existing-browser.js
> +                    await context.close();
так в примерах, видимо нет

2023-07-04 17:56 UTC, DudaGod commented on src/browser/existing-browser.js
> +        await this._session.switchToWindow(newWindow);
> потому что вибдрайверу нужно иметь активное окно. просто закрытием других вкладок неактивное окно не становится активным

Так другие же все окна тоже закрываются перед этим куском кода и в итоге метод `getWindowHandles` всегда возвращает одно единственное окно. Хочешь сказать активным остается окно которое мы закрыли? (я бы ожидал другого поведения)

Ну и я на нескольких тестах погонял код и не нашел кейса при котором без этого свитчинга тест фейлится. Может у тебя есть пример такого теста?

2023-07-04 17:58 UTC, DudaGod commented on src/browser/existing-browser.js
> +    async _cycleBrowserContext() {
Как переводится я в курсе. Я не могу понять причем здесь цикл. Ведь тут просто перед каждым тестом создается новый браузерный контекст, а старый закрываются. Кмк название `prepareBrowserContext` будет намного понятнее.

2023-07-05 07:38 UTC, rprovodenko commented on src/browser/existing-browser.js
> +dns.setDefaultResultOrder("ipv4first"); //https://github.com/webdriverio/webdriverio/issues/8279
если уберешь это, то будет та ошибка, о которой issue

2023-07-05 07:39 UTC, rprovodenko commented on src/browser/existing-browser.js
> +            return null;
предлагай свои варианты, конкретно на коде

2023-07-05 07:41 UTC, rprovodenko commented on src/browser/existing-browser.js
> +    async _cycleBrowserContext() {
<img width="806" alt="image" src="https://github.com/gemini-testing/hermione/assets/60982217/1be06ccb-ff3d-463c-8d7c-963983690bcb">

но ты можешь свое слово использовать, мне не критично

2023-07-05 07:42 UTC, rprovodenko commented on src/browser/existing-browser.js
> +        await this._session.switchToWindow(newWindow);
>Ну и я на нескольких тестах погонял код и не нашел кейса при котором без этого свитчинга тест фейлится. Может у тебя есть пример такого теста?

странно. у меня фейлилось, но может это другая проблема была. если работает - то окей, выпиливый

2023-07-05 08:13 UTC, DudaGod commented on src/browser/existing-browser.js
> +dns.setDefaultResultOrder("ipv4first"); //https://github.com/webdriverio/webdriverio/issues/8279
Так я и написал потому что у меня без этой настройки работает все и я не смог воспроизвести ошибку. Ну и проверял запуск при разных настройках: локально с devtools, surfwax и локально с selenoid

2023-07-05 08:32 UTC, rprovodenko commented on src/browser/existing-browser.js
> +dns.setDefaultResultOrder("ipv4first"); //https://github.com/webdriverio/webdriverio/issues/8279
> Так я и написал потому что у меня без этой настройки работает все и я не смог воспроизвести ошибку. Ну и проверял запуск при разных настройках: локально с devtools, surfwax и локально с selenoid

интересно. у меня была. проверю еще раз

2023-07-05 12:15 UTC, rprovodenko commented
> На новую логику тестов не хватает

такая логика должна тестироваться интеграционными тестами, создал таску https://st.yandex-team.ru/HERMIONE-1063

2023-07-05 12:36 UTC, DudaGod commented
> такая логика должна тестироваться интеграционными тестами, создал таску

Это внешний репо и ссылки на внутренности лучше не оставлять (отредактировал твой коммент).
Пока интеграционных тестов нет предлагаю набросать простых юнитов. Без тестов новую функциональность мы стараемся не вливать.

2023-07-06 08:16 UTC, rprovodenko commented on src/browser/existing-browser.js
> +dns.setDefaultResultOrder("ipv4first"); //https://github.com/webdriverio/webdriverio/issues/8279
удивительно, перестало происходить. странно. давай выпилим

2023-07-06 08:17 UTC, rprovodenko commented
> Пока интеграционных тестов нет предлагаю набросать простых юнитов. Без тестов новую функциональность мы стараемся не вливать.

Юнит тесты не для этого сделаны. это будут бессмысленные тесты, которые ничего не проверяют, только усложняют разработку.

2023-07-06 09:07 UTC, DudaGod commented
> Юнит тесты не для этого сделаны. это будут бессмысленные тесты, которые ничего не проверяют, только усложняют разработку.

Не согласен. Данные тесты помогут не пропустить баг при последующих изменениях кода. Тем более, что интеграционных тестов сейчас нет. Хорошей практикой является миксовать эти тесты (больше юнитов и меньше дорогих интеграционных).

> Юнит тесты нужны для тестирования внутренней логики, не для тестирования интеграции с внешним АПИ

По такой логике любой npm пакет тоже является внешним API. И получается все нужно тестировать интеграционными тестами, которые довольно дорогие и все кейсы ими покрыть не получится. Предлагаю в чате пообщаться.

2023-07-06 15:22 UTC, rprovodenko commented on src/browser/existing-browser.js
> +            return null;
минус предложенного подхода в том, что действительно не учитывается фаерфокс и, например, когда в других браузерах добавится cdp - здесь конечно никто не вспомнит изменить этот код

матчинг по ошибке - согласен с тобой, именно в этом проблема (хотя она как раз при помощи интеграционных тестов решится. но тогда нужно жестко байндится на конкретную версию вебдрайверио).

если getPuppeteer не сработал, значет он не смог вернуть папитир и ты не можешь подключиться к cdp. Какие проблемы с этим ты видишь? какие возможные ошибки могут возникнуть чтобы это стало проблемой?

2023-07-07 07:34 UTC, DudaGod commented on src/browser/existing-browser.js
> +            return null;
> если getPuppeteer не сработал, значет он не смог вернуть папитир и ты не можешь подключиться к cdp. Какие проблемы с этим ты видишь? какие возможные ошибки могут возникнуть чтобы это стало проблемой?

Да там же куча кейсов когда может подключение по CDP может упасть ([исходник](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/BrowserConnector.ts#L83-L153)). Самый простой пример который приходит в голову это пользователь указывает некорректный `browserWsEndpoint` и никуда подключится не может. В итоге мы такую ошибку проигнорируем, хотя не должны.

2023-07-07 07:53 UTC, rprovodenko commented on src/browser/existing-browser.js
> +            return null;
> это пользователь указывает некорректный browserWsEndpoint и никуда подключится не может 

почему юзер будет указывать browserWsEndpoint? он это указывает, когда использует devtools протокол, который мы не поддерживаем. Я ошибаюсь?

2023-10-03 12:16 UTC, closed without merging

2023-10-03 12:16 UTC, DudaGod commented
I'll finish it in a new PR.